### ISSUE TITLE
How to handle pull/push of photos?

### ISSUE THREAD

**Issue by mlutken** [odeke-em/drive#572] opened 2016-01-29 21:55 UTC
Seems I can only access documents, not my photos!

**Comment by canpolat** [comment] 2016-01-30 13:19
`drive` push and pull works for all sorts of files. Could you provide more information about your setup and what commands you are using?

**Comment by odeke-em** [comment] 2016-01-30 18:03
Hello @mlutken thanks for the question and welcome to drive. If you mean  "Google Photos", please take a look at https://github.com/odeke-em/drive/issues/301#issuecomment-125758506.
Thanks @canpolat for taking this one ;)

**Comment by canpolat** [comment] 2016-01-30 18:53
No problem @odeke-em :)

**Comment by mlutken** [comment] 2016-01-30 19:33
Yes I have tried that and it works, but it seems that those two photo foldes are not the same. I can't use the gDrive-photo folder to actually upload photos to photos.google.com... 
At least it seems to me that it does not get updated that way round - only the other.
Or am I wrong ?

**Comment by mlutken** [comment] 2016-01-30 19:34
But the program works really great for gdrive documents :)

**Comment by odeke-em** [comment] 2016-02-04 06:27
@mlutken what you can do is some sort of `drive stat "Google Photos"`. If you were able to follow the steps in that issue's comments, you'll be able to access your "Google Photos" folder with the WebUI and then you can stat and make sure that the folderIds match up then remove the one that doesn't match up and then you can easily use drive with it. Hope this helps.

**Comment by odeke-em** [comment] 2016-03-25 08:48
Closing this issue since works as intended. Please reopen if persists.

**Closed by odeke-em** 2016-03-25 08:48 UTC
