### ISSUE TITLE
"drive pull" arbitrarily erases local drive folder completely

### ISSUE THREAD

**Issue by hleinders** [odeke-em/drive#584] opened 2016-02-10 10:32 UTC
Hello everyone,

I've played around for a while with drive and embedded it into an automatic (sort of) system with .bash_login and .bash_logout and was quite happy with it. Some days ago I build this on a new little Box (Raspberry/Debian 8) and  at least 3 times my local copy vanished without any reason. I've build "drive" from scratch with the newest version (0.3.4).

After recreation of the local Folder "GoogleDrive" and copying .gd/credentials.json from a backup into it, I've executed the command "drive pull GoogleDrive/" several times and always said "n" to abort the action. 

I've noticed that _mostly_ the exec resulted in "Addition count 38 src: 6.41MB\nProceed with the changes? [Y/n]:", which is correct, 
but for no obvious reason in about one of ten calls I've got:

$ drive pull GoogleDrive/
Resolving...
- /
Deletion count 1
Proceed with the changes? [Y/n]:

There were no diffs on the google side, and the next execution of this command gives the correct result again - with a probability of 90% or so. 

I would guess this is related to issue #577 

My versions are:
$ drive version
drive version: 0.3.4
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime:

(Note: This should look different, shouldn't it?)

$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie

$ go version
go version go1.5.3 linux/arm

Best Regards, Harald

Update: I can *not*, repeat: *not* reproduce this with OpenSUSE 42.1 on my Notebook
Same drive version, same go version (linux/amd64, of course).

**Comment by canpolat** [comment] 2016-02-10 18:16
Not sure what is going on here but it could be related to #519 #480 #549

Google API has been somewhat unstable recently. That at least explains the fact that you cannot reproduce it.

**Comment by r-clancy** [comment] 2016-02-10 22:59
I can confirm this as well.

Not a lot of details to give here, but I have a cron job running every 30 mins that runs "drive pull /home/ryan/drive" - it will randomly delete the drive folder at times (set it up a few days ago and it appears to be gone today).

**Comment by CountryBumkin** [comment] 2016-02-10 23:54
This sounds similar to #480 but in the opposite direction for a pull command.

It would appear there is a silent failure or mishandled error from the Google storage which returns no files. The response on a push is to re-send all the files, on a pull all the local files will be deleted to match the nothing that was found in the Google storage.

A possible short term mitigation is to use the --no-clobber or --exclude-ops "delete" options to prevent wipe outs.

A compounding side issue is the use of non-standard terminal io routines that do not follow the linux command output redirections (or contain many \r characters which over writes records), so script log files are incomplete, complicating debugging.

Regards CB

**Comment by odeke-em** [comment] 2016-02-12 05:56
Hello folks, @hleinders thank you for this report and welcome to drive!
Thanks @canpolat, @CountryBumkin and @r-clancy.

As you might have noticed and as previously mentioned, the Google Drive backend has been very unstable. As suggested, please use `--exclude-ops` if this problem is recurring for you, unfortunately this is out of my control when Google Drive's backend doesn't respond properly. However, I'd recommend creating a private API project obtaining a clientId and secret and replacing those in your env as detailed here https://github.com/odeke-em/drive#configuration then performing the OAuth2.0 exchange. This way you won't be affected by erraneous API quota limits on the default credentials moreover shared by very many people around the world. Hope this helps!

**Comment by hleinders** [comment] 2016-02-12 10:09
Hi @odeke-em,

first of all thank you for continuing "drive", well done! :-)

For several reasons I would like to run drive unattended within some automation scripts where using different api keys is not an option. Would it be possible to signal an api error to the outside world by a dedicated error value via os.Exit()? So a wrapper script could implement some retry procedure. Until now drive only answers with 0 or 1 as far as i can see. As a long term unix nerd I'm _really_ fond of return codes. :-)

Best regards, Harald

**Comment by odeke-em** [comment] 2016-02-12 10:20
Hello again @hleinders, thank you for the kind words :)

So an issue was made related to your request for return codes here https://github.com/odeke-em/drive/issues/479. However, unfortunately I didn't get time during my December break to work on it. I'll try to squeeze something in though soon hopefully.

**Comment by hleinders** [comment] 2016-02-12 10:28
@odeke-em,

you're very welcome. :-)
And thanks a lot for creating the issue.

**Comment by Sadi58** [comment] 2016-03-03 13:32
I've just experienced this while working on a bash script to automate some basic synchronization functions.
I'm trying to prevent such a disaster by (1) first getting the total number of items in my local Drive folder, (2) using the output of `drive diff -skip-content-check -ignore-name-clashes -ignore-conflict -ignore-checksum` to check the differences reported, and (3) warning the user about unusual amount of changes -- e.g. if the changes will affect more than half -- and letting the user abort the process without executing the next command in the script, `drive pull -no-prompt -ignore-name-clashes -ignore-conflict -ignore-checksum`.

**Comment by odeke-em** [comment] 2016-03-25 08:58
Hey folks as previously mentioned, please use own API keys otherwise the instability and flaky quota limits are going to manifest this problem. This issue is out of my control as drive will only report what the remote tells it exists or doesn't exist. I'll close this issue as it is a duplicate of #480. Also exit codes have been implemented with PR #608.

**Closed by odeke-em** 2016-03-25 08:58 UTC

**Comment by n-st** [comment] 2018-01-07 04:02
@odeke-em I see the problem with the API, but should `drive` really *ever* be able to delete its own `.gd` directory?  
I'd think that's a detectable error condition, since it is different from "all files in this Drive have been deleted".

**Comment by odeke-em** [comment] 2018-01-07 04:05
@n-st thanks for the ping. 
>... @odeke-em I see the problem with the API, but should drive really ever be able to delete its own .gd directory?

The only way I see that happening is if you've enabled `-hidden` but no it shouldn't. Could you please provide some more context as to how this is happening for you?

**Comment by n-st** [comment] 2018-01-07 04:08
@odeke-em I've written a bit more at https://github.com/odeke-em/drive/issues/577#issuecomment-355797463 (stumbled about that issue before this one). Do let me know if you need any more info.

**Comment by n-st** [comment] 2018-01-07 04:24
Also, please excuse typos, brevity, and crankiness — I just had to restore from backup at 5 a.m.… Will get some sleep and hope it stays alive in the meantime. ;)
