### ISSUE TITLE
Percentage over 100% and negative time during drive pull

### ISSUE THREAD

**Issue by malteseunderdog** [odeke-em/drive#758] opened 2016-10-06 10:08 UTC
> yyy@xxx:~/tom/2016-10-09$ drive version
> drive version: 0.3.8
> Commit Hash: <CURRENT_COMMIT>
> Go Version: <GO_VERSION>
> OS: <OS_INFO>
> BuildTime: 
> jp@dna:~/gdrive-uom/science/tom/2016-10-09$ drive version
> drive version: 0.3.8
> Commit Hash: <CURRENT_COMMIT>
> Go Version: <GO_VERSION>
> OS: <OS_INFO>
> BuildTime: 

``````
+ /tom/2016-10-09/5_myth_debunked.jpg
- /tom/2016-10-09/5_myth_debunked_globalwarmingdeniers.jpg
M /tom/2016-10-09/2016-10-09Issue_JPE.docx
Addition count 1 src: 28.69KB
Deletion count 1 dest: 90.51KB
Modification count 1 src: 21.76KB dest: 12.36KB
Proceed with the changes? [Y/n]:Y
 144352 / 51666 [=========================================================] 279.39% 0```
``````

**Comment by canpolat** [comment] 2016-11-06 13:59
Duplicate of #177

**Comment by odeke-em** [comment] 2016-11-07 06:13
Thanks @malteseunderdog and @canpolat, duplicate in deed. I'll close it in
favor of the earlier open bug.

**Closed by odeke-em** 2016-11-07 06:13 UTC
Labels: bug, duplicate

**Comment by odeke-em** [comment] 2016-11-07 06:29
Thanks for the patience, fixed by PR https://github.com/odeke-em/drive/pull/784.

Please get the latest from master by
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
