### ISSUE TITLE
Push: 'Error 500: Backend Error, backendError' causes duplicates

### ISSUE THREAD

**Issue by raintonr** [odeke-em/drive#523] opened 2015-12-19 09:34 UTC
I recently tried a push and saw this:

```Resolving...
googleapi: Error 500: Backend Error, backendError
```
After this error 'drive' appeared to think that none of my local files were on the destination and proceeded to copy them all, creating duplicates for any that were already there (many).

**Comment by odeke-em** [comment] 2015-12-19 09:36
Hello again @raintonr, thanks for reporting this issue. Yeah the Google Drive backend has been quite unstable for the last month or so and this issue has manifested in https://github.com/odeke-em/drive/issues/519 and https://github.com/odeke-em/drive/issues/480. I think it is a duplicate though of #519

**Comment by raintonr** [comment] 2015-12-19 09:42
Yeah, #519 sounds the same. However, I think it should stop whatever options (quiet or not) have been selected.

**Comment by odeke-em** [comment] 2015-12-23 07:16
As mentioned this is a duplicate of #519. Please make any future comments there.

**Closed by odeke-em** 2015-12-23 07:16 UTC
