### ISSUE TITLE
Rate Limit errors trigger full update

### ISSUE THREAD

**Issue by CountryBumkin** [odeke-em/drive#480] opened 2015-11-12 05:07 UTC
I use drive in this daily script to backup a directory tree on Linux mint 17.2 64 bit.
#!/bin/sh -x
exec > /home/xxxx/edev/drive/Gdrive`date +%Y_%_%d_%H%M`.log                                                                   
exec 2>&1
at 1300 -f ~/edev/drive/Gdrive.sh
#
cd ~/Gdata
drive version
date
drive push -depth -1 -no-prompt --exclude-ops delete --verbose ~/Gdata
date
drive list -depth -1 --sort name -version
exit

No files have changed for several days so the last few log files looked like this....

warning: commands will be executed using /bin/sh
job 163 at Thu Nov 12 13:00:00 2015
drive version: 0.3.2
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 
Wed Nov 11 13:00:00 AEST 2015
Resolving...
Everything is up-to-date.
Wed Nov 11 13:00:54 AEST 2015
/0Archive  v47280
/Documents  v49511
/Pictures  v43220
[snip long list of files]

Today drive attempted to upload the entire dir tree...

warning: commands will be executed using /bin/sh
job 164 at Fri Nov 13 13:00:00 2015
drive version: 0.3.2
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 
Thu Nov 12 13:00:00 AEST 2015
Resolving...
googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded

0 / 1146126235  0.00 % 
512 / 1146126235  0.00 % 497h51m2s
131584 / 1146126235  0.01 % 2h25m15s
164352 / 1146126235  0.01 % 2h19m32s
263168 / 1146126235  0.02 % 1h41m39s
[snip]
4726664 / 1146126235  0.41 % 2h52m19s
4759432 / 1146126235  0.42 % 2h51m56sremoteMod/remoteMkdirAll: `/Pictures` got googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
push: /Pictures/2009-05-05--15.03.58 err: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded

4792200 / 1146126235  0.42 % 2h51m33s
[snip several more rate errors]

Have the rate errors disrupted or aborted the resolving so the entire tree will be uploaded ?

regards CB

**Comment by odeke-em** [comment] 2015-11-12 05:18
Hello again @CountryBumkin,
For starters: did the log show any lines such as "Trying again in <X.Y> seconds"? If not there might be a problem with your installation of packages because it should show you this information if at all you had been using `go get -u` to update and install drive and not just a `git pull` as the dependencies are installed differently. 

drive will try its best to retry an upload, --verbose just shows you the steps. If it all fails, then the line that appeared in your log file 
```shell
$ push: /Pictures/2009-05-05--15.03.58 err: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
```

**Comment by CountryBumkin** [comment] 2015-11-12 05:48
Drive is updated automatically from the PPA, I did not build it.
The text quoted was cut and paste from the log files, maybe some terminal messages are not captured by the redirections in the script file.

**Comment by odeke-em** [comment] 2015-11-12 05:51
CC @shaggytwodope, if I may ask does the PPA have the latest of https://github.com/odeke-em/exponential-backoff? Thanks.

**Comment by shaggytwodope** [comment] 2015-11-12 06:19
@odeke-em Certainly does, +Subproject commit 96e25d36ae36ad09ac02cbfe653b44c4043a8e09

Can see from the old commit here:
https://github.com/shaggytwodope/drivedebpackage/commit/a1f36e69bff72256e401d02298d910d16aa63d1d

I don't always update the commits for the ppa package. But the snapshot uploaded to the ppa SHOULD have the git repo info as well if need be for reference. If something is broken I can push an update parhaps using all current copys of stuff.

**Comment by bellera** [comment] 2015-11-12 10:32
I started using drive some days ago in order to push local files to Google Drive.

I did it without problems until today. Now:

got googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded

Local  o.s. and  drive binaries have not been updated since I started using it.

Ubuntu 12.04 LTS 64 bit
drive version: 0.3.1

Not Quota exceeded for the user. I'm using a Google Apps For Education account. No limits.

Account type:	UNLIMITED
Bytes Used:	1247085125           (1.16GB)
Bytes Free:	10995116277760       (10.00TB)

Looking at Google for the error other applications such rclone have the same problem.

What to do?

Thanks,

Josep Pujadas-Jubany

**Comment by matthewlenz** [comment] 2015-11-12 13:43
There are other drive api projects with people reporting the same errors.  I just started seeing them the last couple days in my scripts at randoms times.  I think google changed something.

**Comment by bellera** [comment] 2015-11-12 13:46
Is the upload (push) limited to 2 GiB per day?

I'm wondering it because other users that I totally uploaded to Gdrive had less than 2 GiB.

And now I'm seeing that for the "problematic" user I had 2 GiB uploaded and my total to upload is about 7 GiB.

**Comment by odeke-em** [comment] 2015-11-12 13:47
Hello @bellera and @matthewlenz, welcome to drive and thanks for that!
Yeah I have the exact same situation as @bellera, same Education account Unlimited and yet when I just `drive stat file` I got a rateLimitExceeded error too. I'll ping them shortly.

**Comment by monojp** [comment] 2015-11-12 14:03
Hi again, I'm currently running into the same error. Have not done any updating recently, but I am running the latest version I guess (0.3.2). I also don't know about any mass-syncs I did, so I see no reason why I would have exceeded any limits. Also I don't use an education account, so maybe this is a global bug "upstream" in the drive protocol / servers atm?

**Comment by odeke-em** [comment] 2015-11-12 14:05
For a second I thought my account had been hacked since a single `drive stat` on a lone file can't be that heavy. However, I think maybe they cut down the qps offered to each project and given that drive's daily limit was 1,000,000,000 requests daily(1 billion) and 1000 requests per second (qps) per user, so they probably changed something. However I don't have access to that API project as Google owns it but @rakyll does have access to it. I've emailed a Google Developer to help me contact someone.

**Comment by bellera** [comment] 2015-11-12 14:23
I started uploading another user with 11 GiB to push.

After some uploading (about 45 MiB) began the error.

**Comment by JernejJerin** [comment] 2015-11-12 17:08
Just jumping in to report that I have the same issue about `googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded`. I hope you guys find a solution quick, but if Google lowered number of requests per day per user then I guess we are out of luck :(

**Comment by bellera** [comment] 2015-11-12 22:05
@odeke-em said:

maybe they cut down the qps offered to each project...

So, @JernejJerin, the problem is not "per user". It's for "all users" using this project!

Now I'm at home, with my @gmail.com and tried to pull mi Google Drive as I did the 29-october for testing this application.  I got:

$ drive pull
Resolving...
googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded

So, it seems that, for the moment, this solution has been unusable!

Terrible! I wanted to upload all my school users!

**Comment by rakyll** [comment] 2015-11-12 22:08
@bellera:

Drive API has daily quota allowance which is 1 billion requests per day. The project is currently using ~0.6%. The API also has a QPS limit per user which is 10. I am going to talk to the team to increase the per user quota.

**Comment by rakyll** [comment] 2015-11-12 22:22
This is being investigated now, thanks for the report.

**Comment by odeke-em** [comment] 2015-11-13 03:34
Sorry for the late reply y'all. Was out all day for a practical class assignment. 
@bellera it is unfortunate but hopefully this can be resolved soon.
@rakyll thanks for advocating for us and for getting this looked at!

**Comment by bellera** [comment] 2015-11-13 10:03
drive push -fix-clashes -quiet
Resolving...
4158358499 / 7971765758 [============================================================>-------------------------------------------------------] 52.16 % 2h41m52s

Working! Thanks!

**Comment by miketotman-sd** [comment] 2015-11-13 23:00
We are also experiencing this issue, which started on Wednesday, Nov 11.

We have a script which runs nightly on a number of servers and all of them started having this error on the same night.

I went in and deleted some old files in one directory and tried to push them with "drive push ." on each of the servers. 5 out of 7 servers reported the error but were able to sync. 2 of them failed to do anything.

**Comment by miketotman-sd** [comment] 2015-11-13 23:12
Coming back an hour later it seems to be OK now. In the interim I had also deleted some of the files directly in the Google Drive folder. My main concern was, as mentioned above, that sometime it never succeeded at all.

**Comment by odeke-em** [comment] 2015-11-15 23:43
Looks like this was solved, thanks everyone for your patience. Thanks to the advocacy and help from @rakyll we got our quota bumped up quite a bit so we shouldn't be getting such problems anymore 
@rakyll you the real MVP
![mvp](https://cloud.githubusercontent.com/assets/4898263/11171846/caa8f26a-8bb7-11e5-8b94-e84d63f3d92d.gif)

**Comment by shaggytwodope** [comment] 2015-11-15 23:46
@odeke-em awesome, thank god is wasnt something I did lol.

**Comment by odeke-em** [comment] 2015-11-15 23:47
Ahaha nah, my bad if it came off that way, I was just trying to diagnose the problem. It wasn't anything in our direct control that caused it.

**Comment by shaggytwodope** [comment] 2015-11-15 23:53
Not at all mate, just being silly.

**Comment by rakyll** [comment] 2015-11-16 00:03
@odeke-em aww, thanks :)

Please update this thread if anyone happens to come across an unlikely rate limit error. They bumped the quota a bit, but not sure if the issue is permanently resolved.

**Comment by odeke-em** [comment] 2015-11-16 00:08
@rakyll Ah I see, for sure. It has been working alright for me for the past two days but we'll def keep vigilant for any errors. Whenever you get the confirmation, please let me know :)

**Comment by CountryBumkin** [comment] 2015-11-16 05:57
It is good to solve the particular problem but it would be useful to address to fail unsafe aspect of the resolving. It is common to run drive with unattended scripts and the present fail unsafe ( for whatever reason) aspect of resolving to push (or probably pull) the entire folder tree contents would be quite disruptive.

It would be more appropriate that if there is any uncertainty in resolving to do nothing and exit with a suitable status.

**Comment by bellera** [comment] 2015-11-16 06:24
I confirm that I don't have more "rate limit errors".

However, migrating users from local server storage (Ubuntu 12.04 LTS 64 bit) to Google Drive I have to use

drive push

three times before receiving the message "everything is to date"

I'm pushing 10-15 GiB for each user. Anybody has access to hte user folder when I'm pushing it. So, no changes are made since the migration process is started.

If you think I have to open a new thread for this, let me know. Thanks!

**Comment by odeke-em** [comment] 2015-11-16 08:25
@CountryBumkin good points right there. Currently drive will attempt a best try with an exponential back off then finally fail. If am thinking what I think you are thinking (correct me if am wrong) is you'd like a failure asap and the appropriate error code. Sure, but a mode to fail on first try is going to cause you a lot of headache as rateLimitExceeded errors are common and expb just attempts to alleviate the problem, you can examine this by passing in flag `--verbose` during a push/pull. In this issue's case, the max retries were exhausted on every single attempt because of a problem with quota allocations/limiting on the remote end. As mentioned in #479, I'd be happy to implement the bash error codes but time isn't something I have a lot of since it will require defining a new error conformer centric to drive then going through each usage of error. I'd review  a PR though or give guidance if you'd like :) End of Semester + Exams are fast approaching for me that's why I can only promise that in a month and a half or two.
@beller good to know it is working again for you too. Before you open an issue, please make sure you are using the latest at tip because of https://github.com/odeke-em/drive/issues/477

**Comment by CountryBumkin** [comment] 2015-11-16 10:27
The most important aspect is to ensure the integrity of the overall resolving process. There should be some examination of how this error corrupted the resolving process but the program still tried to proceed.

If any error occurs in the resolving process whose retry success cannot be guaranteed then the entire resolving process should be aborted, re-initialized and started again, up to some reasonable number of re-tries.

If rate limit errors are potentially unrecoverable then the exponential back off parameters of the overall resolving process could include conservative rate limiting inside drive that becomes more severe as the retry count rises to minimize the chance of errors.

Only after multiple failed tries of repeating the entire resolving process should drive flag a fatal error and abort.

**Comment by miketotman-sd** [comment] 2015-11-17 18:32
I, like the OP, am using the drive command in a script to backup some files to Google Drive. Our scripts run at night via cron, but for the last few days it fails every night. If I go into each server and run the effective command (`drive push -quiet -no-clobber *.gz`) it succeeds. I changed our scripts to execute at staggered intervals (10 min apart) and that did not fix it.

If I look at the Google Console for the Drive API project I set up for this, it doesn't show an excessive amount of requests or traffic. We have a Google Apps for Business account and are nowhere near our storage limit either.

This is what the log shows:
> ...
> Pushing all backup files to Google Drive
> Resolving...
> googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded
> Pushed successfully.
> ...

Any ideas what to look for to resolve this issue for me?

**Comment by odeke-em** [comment] 2015-11-18 15:16
Hello @miketotman-sd so I guess for other projects the quota hasn't yet fixed. As mentioned, @rakyll hasn't yet received a confirmation that it is fixed so for now please use drive's config which has a higher quota and should be working alright for now.

**Comment by miketotman-sd** [comment] 2015-11-18 17:59
What exactly do you mean by "use drive's config" -- do you mean I should use drive's default client ID & secret and re-initialize my drive folders? Couldn't I just ask for a quota increase for our own project credentials?

Also, I don't understand why this fails when run automatically but succeeds when run manually. Presumably it should be doing the same thing, right? Why the difference?

**Comment by odeke-em** [comment] 2015-11-18 20:13
@miketotman-sd yes in deed, the default client Id and a reinit. I don't know about asking for a quota increase, that might work but the actual quota rationing problem as mentioned previously hasn't yet been resolved on Google Drive's backend -- it might just a higher quota for drive might be masking the problems or this project got a different configuration set up, this is just my speculation as I wasn't there when they were trying to mitigate the problems.

About cron, I don't run drive on cron jobs, I just do everything manually as that's my motivation for this project :) However, please try with drive's default credentials and let me know what happens.

**Comment by miketotman-sd** [comment] 2015-11-22 05:27
Using the default drive config worked for all our servers. I'd still prefer to use our own config but this will do for now.

**Comment by miketotman-sd** [comment] 2015-12-04 19:21
I just got a bunch of these errors again, like the user in the referenced issue (#513), when calculating the update for a push after deleting a bunch of files.

**Comment by gauteh** [comment] 2015-12-07 08:25
This seems to be related to bandwidth for me, if I am on a connection with low upload bandwidth it does not happen. I just got the following error as well:

after a lots of:

    googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded

during resolve while pushing a directory (using -no-clobber):

```
unexpected fault address 0x0
fatal error: fault
[signal 0x7 code=0x80 addr=0x0 pc=0x51af05]

goroutine 1 [running]:
runtime.throw(0x8fd638, 0x5)
	/usr/lib/go/src/runtime/panic.go:527 +0x90 fp=0xc82004d738 sp=0xc82004d720
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:21 +0x10c fp=0xc82004d788 sp=0xc82004d738
github.com/odeke-em/drive/src.(*Change).op(0xc821962100, 0x2)
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/drive/src/types.go:437 +0x65 fp=0xc82004d7b0 sp=0xc82004d788
github.com/odeke-em/drive/src.(*Change).Op(0xc821962100, 0x2)
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/drive/src/types.go:525 +0x3a fp=0xc82004d7c8 sp=0xc82004d7b0
github.com/odeke-em/drive/src.sift(0xc822496000, 0x5563, 0x5800, 0xc821bc6000, 0x10, 0x10, 0x0, 0x0, 0x0)
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/drive/src/changes.go:581 +0xa9 fp=0xc82004d848 sp=0xc82004d7c8
github.com/odeke-em/drive/src.(*Commands).resolveConflicts(0xc82000b100, 0xc822496000, 0x5563, 0x5800, 0xc822d2a001, 0x5563, 0x5800)
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/drive/src/push.go:163 +0xdd fp=0xc82004d978 sp=0xc82004d848
github.com/odeke-em/drive/src.(*Commands).Push(0xc82000b100, 0x0, 0x0)
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/drive/src/push.go:102 +0xbd1 fp=0xc82004dc98 sp=0xc82004d978
main.(*pushCmd).Run(0xc8200d48c0, 0xc82000a2f0, 0x1, 0x1, 0xc8200c3710)
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/drive/cmd/drive/main.go:793 +0x237 fp=0xc82004dd50 sp=0xc82004dc98
github.com/odeke-em/command.Run()
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/command/command.go:202 +0xaa fp=0xc82004dd90 sp=0xc82004dd50
github.com/odeke-em/command.ParseAndRun()
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/command/command.go:209 +0x19 fp=0xc82004dd98 sp=0xc82004dd90
main.main()
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/drive/cmd/drive/main.go:120 +0x1ffe fp=0xc82004df50 sp=0xc82004dd98
runtime.main()
	/usr/lib/go/src/runtime/proc.go:111 +0x2b0 fp=0xc82004dfa0 sp=0xc82004df50
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82004dfa8 sp=0xc82004dfa0

goroutine 17 [syscall, 5 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, 5 minutes]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, 5 minutes, locked to thread]:
runtime.gopark(0x9d27b0, 0xc82002e728, 0x8ff058, 0x6, 0x440018, 0x2)
	/usr/lib/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002e728, 0x0, 0x18)
	/usr/lib/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002e728)
	/usr/lib/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/lib/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [runnable]:
syscall.Syscall(0x1, 0x2, 0xc821fe2cb0, 0x4, 0x4, 0x4, 0x0)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.write(0x2, 0xc821fe2cb0, 0x4, 0x8, 0xc820070f70, 0x0, 0x0)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:1064 +0x5f
syscall.Write(0x2, 0xc821fe2cb0, 0x4, 0x8, 0x1, 0x0, 0x0)
	/usr/lib/go/src/syscall/syscall_unix.go:176 +0x4d
os.(*File).write(0xc820030018, 0xc821fe2cb0, 0x4, 0x8, 0x0, 0x0, 0x0)
	/usr/lib/go/src/os/file_unix.go:232 +0xaa
os.(*File).Write(0xc820030018, 0xc821fe2cb0, 0x4, 0x8, 0x1, 0x0, 0x0)
	/usr/lib/go/src/os/file.go:139 +0x8a
fmt.Fprintf(0x7fe9d8fbb1e8, 0xc820030018, 0x8fa408, 0x3, 0xc820041f20, 0x1, 0x1, 0x4, 0x0, 0x0)
	/usr/lib/go/src/fmt/print.go:189 +0xb2
github.com/odeke-em/cli-spinner.(*Spinner).spin.func1(0xc82000b180)
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/cli-spinner/spinner.go:99 +0x351
created by github.com/odeke-em/cli-spinner.(*Spinner).spin
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/cli-spinner/spinner.go:103 +0xce

goroutine 9 [chan receive, 5 minutes]:
github.com/odeke-em/drive/src.(*Commands).Push.func1(0xc8200d62a0, 0xc820011da0, 0xc82000b100)
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/drive/src/push.go:51 +0x43
created by github.com/odeke-em/drive/src.(*Commands).Push
	/tmp/yaourt-tmp-gaute/aur-drive/src/drive-0.3.3/src/github.com/odeke-em/drive/src/push.go:55 +0x335

goroutine 16390 [IO wait]:
net.runtime_pollWait(0x7fe9d595d6c0, 0x72, 0xc8200122b0)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc821508920, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc821508920, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8215088c0, 0xc821bfa000, 0x1000, 0x1000, 0x0, 0x7fe9d8fb7050, 0xc8200122b0)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82127a668, 0xc821bfa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc821bcd170, 0x7fe9d59441b8, 0xc82127a668, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc822830580, 0x9d2817, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc822830580, 0xc821100000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7fe9d594cc28, 0xc822830580, 0xc8225e6c08, 0xc821100000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8219be240, 0xc821100000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8216302a0)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8216302a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8225e6bb0)
	/usr/lib/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:685 +0xc78

goroutine 16256 [select]:
net/http.(*persistConn).writeLoop(0xc821905550)
	/usr/lib/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:686 +0xc9d

goroutine 16391 [select]:
net/http.(*persistConn).writeLoop(0xc8225e6bb0)
	/usr/lib/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:686 +0xc9d

goroutine 16255 [IO wait]:
net.runtime_pollWait(0x7fe9d5961ae0, 0x72, 0xc8200122b0)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc821a89090, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc821a89090, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc821a89030, 0xc8214f2000, 0x2000, 0x2000, 0x0, 0x7fe9d8fb7050, 0xc8200122b0)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc821f9c020, 0xc8214f2000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8223606f0, 0x7fe9d59441b8, 0xc821f9c020, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8225ee840, 0x9d2817, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8225ee840, 0xc8210e3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7fe9d594cc28, 0xc8225ee840, 0xc8219055a8, 0xc8210e3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82180e500, 0xc8210e3000, 0x1000, 0x1000, 0xc8223387d0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc821b37e00)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc821b37e00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc821905550)
	/usr/lib/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/lib/go/src/net/http/transport.go:685 +0xc78
```

**Comment by gauteh** [comment] 2015-12-11 10:05
What happens when there is an rateLimitError during push? does drive re-try?

**Comment by ikwyl6** [comment] 2016-03-06 18:00
Haven't used drive for a while, updated it today to 0.3.5 and did a `drive pull` on a dir and got this:

```
Resolving...
googleapi: Error 429: Rate Limit Exceeded, rateLimitExceeded
 | 
clashes detected. Use `ignore-name-clashes` to override this behavior or `fix-clashes` to try fixing this
```

**Comment by HyperCriSiS** [comment] 2016-06-04 19:05
I have the same issue with GoogleDrive. Cannot transfer the files.
Error 403: Rate Limit Exceeded, rateLimitExceeded - low level retry 3/10

**Comment by HyperCriSiS** [comment] 2016-06-04 19:56
I found out howto fix it :)
1. Open https://console.developers.google.com
2. In the section "Google Apps APIs" go to "Drive API"
3. Push enable
4. Credentials --> Create Credentials --> OAuth Client ID
5. Application type --> other
6. Reconfigure the account in rclone and enter the just created ClientID and secret
7. Have Fun :)

**Closed** 2016-09-17 22:52 UTC
Labels: google-drive remote API error

**Comment by odeke-em** [comment] 2016-09-17 22:59
Hey y'all, please get the latest. Thank you very much for all the patience and the bug reports.
Finally fixed this problem that was caused by not properly relaying remote resolution errors back to the callers. The fix is in https://github.com/odeke-em/drive/pull/741. Please get the latest code and even in these rate limit/resolutions problems drive will now be able to relay encountered errors and properly abort instead of performing the wrong behavior.

**Comment by asd-and-Rizzo** [comment] 2016-11-29 14:55
I see next now. Question about strategy. I see when one file failed, it goes to next. Should it stop on one file and to exp retry on it instead of going to next? 

And here we have potentially infinite operation, so it would be great for noobs users show `CTRL+C to abort` as in other basic tools. May be some other hotkey as `Esc to abort`?

```
push: /courseera/progfun-002/hello-project/bin/greeter/LearningSuite.class err: googleapi: Error 403: User rate limit exceeded, userRateLimitExceeded

push: /courseera/progfun-002/hello-project/bin/greeter/TestRepl.sc err: googleapi: Error 403: User rate limit exceeded, userRateLimitExceeded

push: /courseera/progfun-002/hello-project/bin/week1 err: googleapi: Error 403: User rate limit exceeded, userRateLimitExceeded

push: /courseera/neuralnets err: googleapi: Error 403: User rate limit exceeded, userRateLimitExceeded
dlahoda@dlahodad2:/stuff/dlahoda/gdrive/courseera$ drive version
drive version: 0.3.8.1
Commit Hash: '9ce18db69196f53da028fab0ba9621dc33a23656'
Go Version: go1.6.2
OS: linux/amd64
BuildTime: 2016-11-20 21:31:48.2487148 +0300 +03
dlahoda@dlahodad2:/stuff/dlahoda/gdrive/courseera$ 
```

**Comment by gramels** [comment] 2017-04-08 09:01
I get 

`Error 403: User rate limit exceeded, userRateLimitExceeded
`
doing mass touching

`drive touch  -matches
`
on a fast 1gig/s symetric fiber connection.

**Comment by RiaanLab** [comment] 2018-12-17 12:02
I also get a "got googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded"

I have tried increasing the chunk size to 64MiB to see if it is data rate issue or a "number of API requests" issue. The number of 403 instances increases when the chunk size increases. So it seems to be a data rate issue rather than a number of requests issue.

Running Master branch as on 17/12/2018.

**Comment by Anton-V-K** [comment] 2019-03-03 16:50
My script faced this problem on the 22nd of February. It had been running smoothly until then for ~2 months uploading ~80 MB of data each day.
First it was the error like `Failed to determine free space: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded`, the next day it was like `Failed to find root dir: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded`...
Less than 1GB is used at Google Drive.
