### ISSUE TITLE
Percentage over 100% and negative time during drive push

### ISSUE THREAD

**Issue by asd-and-Rizzo** [odeke-em/drive#708] opened 2016-08-18 09:11 UTC
I did `drive push` on whole drive. After some time I saw that my push is 550% and minus 11 minutes as in screenshot.

![over_percentage_and_time](https://cloud.githubusercontent.com/assets/757125/17768450/acd6ae80-653c-11e6-98c5-3c2018c38a99.png)

What commands to run to get version of gdrive/go/ubuntu? Other information?

**Comment by asd-and-Rizzo** [comment] 2016-08-18 11:02
After hour of waiting got next:
```
Proceed with the changes? [Y/n]:y
 1025210158 / 140824489 [======================================================================================================================================= 1025217144 / 140824489 [=======================================] 728.01% -27m6s
 1103808349 / 140824489 [============================================================================================================] 783.82% 1h37m51s

push: /private/courseera/progfun-002/streams/target/streams err: googleapi: Error 403: User rate limit exceeded, userRateLimitExceeded

```

I think hundreds of these errors. Push finished.

**Comment by malteseunderdog** [comment] 2016-09-20 16:02
I see this so often ... is push broken?

> Deletion count 4710 dest: 877.00MB
> Modification count 1 src: 1.17KB dest: 1.17KB
> Addition count 36 src: 2.02MB
> Proceed with the changes? [Y/n]:Y
>  921720078 / 2123754 [====================================================================================================================================================================] 43400.51% 18m36s
> 
> push: /lecturing/CPS3228_Data_Science_From_Data_To_Knowledge/assignment/submissions/Daniela Galea_2093_assignsubmission_file_Assignment .zip err: googleapi: Error 403: User rate limit exceeded, userRateLimitExceeded
> 
>

**Comment by asd-and-Rizzo** [comment] 2016-09-20 19:34
Seems push may finish correctly. At least I have  seen 100.6% finished push with no errors today.

**Comment by canpolat** [comment] 2016-11-06 13:59
Duplicate of #177

**Comment by odeke-em** [comment] 2016-11-07 06:14
Thanks @canpolat, closing in favor of the earlier open bug.

**Closed by odeke-em** 2016-11-07 06:14 UTC

**Comment by odeke-em** [comment] 2016-11-07 06:29
Thanks for the patience, fixed by PR https://github.com/odeke-em/drive/pull/784.

Please get the latest from master by
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
