### ISSUE TITLE
[CLOSED - duplicate]Can't install it.

### ISSUE THREAD

**Issue by hekri-d** [odeke-em/drive#630] opened 2016-04-28 17:07 UTC
Running  `go get -u github.com/odeke-em/drive/cmd/drive` spits out the error `# golang.org/x/net/context/ctxhttp
../gopath/src/golang.org/x/net/context/ctxhttp/ctxhttp.go:35: req.Cancel undefined (type *http.Request has no field or method Cancel)
`
The same happens when trying to run main.go from the manually downloaded source. 

Running openSUSE LEAP 42.1.

**Comment by shaggytwodope** [comment] 2016-04-28 17:27
This looks like a duplicate of #627, basicly go needs to be updated to 1.5 or 1.6 series.

**Comment by shaggytwodope** [comment] 2016-04-28 17:29
@odeke-em unsure of 1.4, but I think may have to edit readme to reflect the need for go 1.5+.

**Comment by hekri-d** [comment] 2016-04-28 17:37
Thank you for the answer. I'll try to update my go version and see what happens. It takes a lot of time to download for 81MB though.

**Comment by hekri-d** [comment] 2016-04-28 17:58
Yup. Updating go to 1.6 fixed this issue.

**Comment by odeke-em** [comment] 2016-04-29 08:09
Thanks for the reminder y'all. I'll update the README right now.

**Closed** 2016-04-29 08:15 UTC
