### ISSUE TITLE
Can't pull files (err:download :failed for url)

### ISSUE THREAD

**Issue by gmgarciam** [odeke-em/drive#766] opened 2016-10-14 22:04 UTC
pull: /Google Photos/MAKEUP_20161008232840_save.jpg err: download: failed for url https://googledrive.com/host/1lX8t7itoTkiBqD2PrFOeeC6tAB4AQhcebA. StatusCode: 404
 0 / 28139364 [----------------------------------------------------]   0.00% 16s 

I keep getting these kinds of error messages. before it would be once in a while and now it consistently stops me from pulling files.

**Comment by odeke-em** [comment] 2016-10-15 01:43
Hello there @gmgarciam, thank you for the issue and welcome to drive!

Please get the latest code from master by
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```

You are getting that error because Google shut down web hosting on August 31st 2016. This issue is a duplicate of https://github.com/odeke-em/drive/issues/764 and the notice of shutdown is https://support.google.com/drive/answer/2881970?hl=en.

**Comment by gmgarciam** [comment] 2016-10-15 01:52
All good now, thanks!

**Comment by odeke-em** [comment] 2016-10-15 02:08
Glad to know it is working alright.

I'll close the issue, but if the symptoms persist, please feel free to reopen it or to file other issues.
Thanks.

**Closed by odeke-em** 2016-10-15 02:08 UTC
