### ISSUE TITLE
drive depends on non-canonical path for drive api imports.

### ISSUE THREAD

**Issue by pefoley2** [odeke-em/drive#398] opened 2015-09-26 18:33 UTC
Running go get -u all results in the below warning:
package github.com/google/google-api-go-client/googleapi: code in directory /home/peter/go/src/github.com/google/google-api-go-client/googleapi expects import "google.golang.org/api/googleapi"

This is caused by https://golang.org/s/go14customimport.

#397 resolves this by using the canonical url to import the drive api.

**Comment by odeke-em** [comment] 2015-09-26 18:36
Hello @pefoley2, thanks for reporting this.
For starters, what version of Go are you using? What is your OS?
Also that doc is like from June 2014, so if there is some import breaking, it must be recent in the Google Go API client.

**Comment by pefoley2** [comment] 2015-09-26 18:37
It's not actually broken, it's just a warning.
I'm using go version go1.5.1 linux/amd64

**Comment by odeke-em** [comment] 2015-09-26 18:39
Thanks for the info. Let me jump out and go grab my computer and test it out.

**Comment by odeke-em** [comment] 2015-09-26 19:26
Hello @pefoley2, unfortunately I can't reproduce your issue.

```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen && drive version && date
drive version: 0.3.0
Commit Hash: 'f95eebeb5a019339295ee13aaa9c9b909d72dbd3'
Go Version: go1.5.1
OS: darwin/amd64
BuildTime: 2015-09-26 13:26:11.855938113 -0600 MDT
Sat 26 Sep 2015 13:26:14 MDT
```

**Comment by pefoley2** [comment] 2015-09-26 19:28
Try running `go get -u all`.
This only showed up when I tried to update all the go packages on my system including drive.

**Comment by odeke-em** [comment] 2015-09-26 19:30
I have a crap tonne of go packages it could take me hours yet I've got to go out in a few minutes.
But even removing all drive's packages as well as drive and starting a fresh doesn't give this warning.

**Comment by pefoley2** [comment] 2015-09-26 19:53
My output from `go get -u all` is here: http://sprunge.us/RQdZ
I can reproduce the warning with `go get -u github.com/google/google-api-go-client/googleapi` as well as a simple `go get -u all`
If I add #397 to my local copy of drive in `$GOPATH`, delete the `$GOPATH/github.com/google/google-api-go-client` directory, run `go get -u github.com/odeke-em/drive/drive-gen` again, then when I run `go get -u all` I don't get the warning.
It might be easier to reproduce if you setup a temporary GOPATH with only drive installed. 
The updated url I changed the code to refer to is mentioned at https://github.com/google/google-api-go-client/blob/master/README.md, so it looks like this is the new official url, although the old one still works for now.

**Comment by odeke-em** [comment] 2015-09-26 20:45
Alright, gotcha. By the time this is tripping out, then it is safer to use the canonical URL. I just wanted to cover all the bases. Thanks for reporting and advocating this issue!

**Comment by odeke-em** [comment] 2015-09-26 20:53
Fixed by PR https://github.com/odeke-em/drive/pull/397

**Closed by odeke-em** 2015-09-26 20:53 UTC
Labels: enhancement
