### ISSUE TITLE
Starred: separate trashed from untrashed files.

### ISSUE THREAD

**Issue by ManuCart** [odeke-em/drive#515] opened 2015-12-07 14:43 UTC
It's a small bug.
When I download starred files with
````drive pull --quiet --starred --all ````
The starred files in trash bin are pull too
How to correct this?

**Comment by odeke-em** [comment] 2015-12-07 15:48
Thanks @ManuCart for reporting this. So the issue is separating trashed and untrashed starred files.
PR coming up in a second.

**Comment by odeke-em** [comment] 2015-12-07 15:53
Please get the latest from master. This issue was auto closed by the commit :) Please re-open if it persists.

**Closed** 2015-12-07 15:53 UTC
Labels: bug, enhancement
