### ISSUE TITLE
.csv and .csv.ods reported as clashes

### ISSUE THREAD

**Issue by berni421** [odeke-em/drive#615] opened 2016-04-06 21:53 UTC
A .csv file, when opened in google drive creates a new google documents file. e.g.

text.csv
test.csv of type google sheets

These are reported as clashes. A pull operation could instead take account of the document type and safely download:-

test.csv
test.csv.ods

**Comment by odeke-em** [comment] 2016-04-29 08:51
Hello there @berni421, thank you for reporting this and welcome to drive.

So that's a weird bug remotely on Google Drive that I too have experienced where it duplicates files. However, I don't think drive should be concerned with trying to auto-ignore different file types on a name clash, because a name clash itself is two or more files with the same path. There are ways of resolving clashes, [`rename`](https://github.com/odeke-em/drive#rename), as well [`fix-clashes`](https://github.com/odeke-em/drive#clashes).

You can also pull and export on specific files by [`file-id`](https://github.com/odeke-em/drive#fileid-retrieval)

IMO this is working as intended. Closing it, please reopen if you think otherwise. Thanks.

**Closed by odeke-em** 2016-04-29 08:51 UTC
