### ISSUE TITLE
Possibility of using SQLite (or a similar database) for indices

### ISSUE THREAD

**Issue by js-ojus** [odeke-em/drive#239] opened 2015-06-18 13:28 UTC
@odeke-em : A suggestion.  The indices could be stored in an SQLite database (or a similar, small, embedded database).  That should help speed up comparisons when large directories or directory trees are involved.

**Comment by odeke-em** [comment] 2015-06-18 15:35
Duplicate of https://github.com/odeke-em/drive/issues/106

**Comment by js-ojus** [comment] 2015-06-18 17:04
Ah ... I see, @odeke-em!  I should have searched thoroughly.  My apologies!

**Comment by odeke-em** [comment] 2015-06-18 17:05
No worries, actually I think your title gets straight to the point :) I should have made the original one's title more explicit.

**Closed** 2015-06-21 10:57 UTC
Labels: duplicate
