### ISSUE TITLE
Make DRIVE_GOMAXPROCS command line argument and fix to allow only 1 thread

### ISSUE THREAD

**Issue by raintonr** [odeke-em/drive#405] opened 2015-10-01 17:53 UTC
IMHO, all options should be either set with command line arguments, or environment variables. Mixing the two is inconsistent and confusion.

Having discovered DRIVE_GOMAXPROCS (see https://github.com/odeke-em/drive/issues/401#issuecomment-144796687) I tried using this.

I think this should be made a command line option.

Regardless of how this is set, it seems to be not working quite how it should.

During a push, setting this variable to 1 yields a message showing 2 concurrent uploads! Setting to zero seems to have no effect and the default 5 files are shown being processed concurrently.

Hence there seems to be no way to limit uploads to a single file.

**Comment by odeke-em** [comment] 2015-10-01 18:55
Hello again @raintonr.
I don't know about making it a command line argument, because that's gonna be awkward for a command line option but you can always do something like
'DRIVE_GOMAXPROCS=1 drive push [options...]'
Upcoming is the ability to use .driverc files.

Also could we first resolve the previous issue before jumping onto this?

Thanks

**Comment by raintonr** [comment] 2015-10-01 19:32
Just making a note. What about when the value is '1' but it still reports pushing 2 files at a time?

**Comment by odeke-em** [comment] 2015-10-01 19:34
Gotcha. For sure, I'll have to investigate that sometime, am in class the whole day so probably when I get back home or over the weekend when I get a break :)

**Comment by odeke-em** [comment] 2015-10-02 02:22
I finally made it back home and can be able to debug. Would you be able to reproduce maxprocs at 1 when you saw 2 instead? Send a screenshot of possible. I think I have an idea of what might be perceived

**Comment by odeke-em** [comment] 2015-10-21 16:19
Hello @raintonr, 
* I won't be changing the semantics of DRIVE_MAXPROCS as it is an env variable that users can set only once or as they please, I've provided a way to set it ie
```shell
$ DRIVE_MAXPROCS=<n> drive ...
```
* It doesn't make sense for a user to try to use -1, 0 for maxProcs. 1 for maxProcs works as expected, if operations complete and print out as fast, that might look confusing but the printing is beyond control of drive.

Closing this, please reopen if you get problems with it.

**Closed by odeke-em** 2015-10-21 16:19 UTC
