### ISSUE TITLE
Getting tons of userRateLimitExceeded errors

### ISSUE THREAD

**Issue by gauteh** [odeke-em/drive#513] opened 2015-12-04 11:21 UTC
Hi,

first while computing the push of a large directory I start to get the error 

```
googleapi: Error 403: User rate limit exceeded, userRateLimitExceeded
```

Later, when the files start uploading (actually these files have been deleted locally) I get the same error. Should these operations have been [batched in some way](https://groups.google.com/forum/#!topic/google-api-objectivec-client/ohw2Y8ueZi0)?

**Comment by odeke-em** [comment] 2015-12-04 15:22
Hello @gauteh thanks for reporting this and welcome to drive.

This issue is a duplicate of https://github.com/odeke-em/drive/issues/480. Please take a look at it.

**Closed** 2015-12-04 15:22 UTC
Labels: duplicate
