### ISSUE TITLE
Remote path doesn't exist

### ISSUE THREAD

**Issue by bausmeier** [odeke-em/drive#46] opened 2015-01-15 18:47 UTC
I have just started using drive and I am trying to push a directory but I see `<nil> remote path doesn't exist` for every file that it tries to push. Is there something I need to do before I push?

The full output is here https://gist.github.com/bausmeier/1178ab3d857d4f1e0920.

**Comment by odeke-em** [comment] 2015-01-15 18:58
what version of drive?

**Comment by bausmeier** [comment] 2015-01-15 19:12
> drive version 0.0.5

**Comment by odeke-em** [comment] 2015-01-15 19:28
Gotcha so the issue is that the file 2014 was never created on the remote but you are pushing 2014/2015...
That is a bug given that it should recognize that the root is not yet on. However if your root is created, then any amount of nesting ie 2014/January/Push/Journals/..... should work.
To solve this, make sure all root directories at least get created e.g
instead of
`$ drive push 2014/2014-01-25\ New\ Camera/`
do
`$ drive push 2014`
And from then on, you can then apply the original command.
Let me know if this helps.

**Comment by bausmeier** [comment] 2015-01-15 19:37
Great, that worked. Thanks for the quick response!

Feel free to close the issue unless you want to track the bug here.

**Comment by odeke-em** [comment] 2015-01-15 19:54
Glad to be of help. I'll work on it when am back home in a couple of hours then we can close it. I had actually started working on this over the weekend: https://github.com/odeke-em/drive/tree/mountpoint-nesting. Feel free to reach out in case of anything.

**Closed** 2015-01-27 13:45 UTC
