### ISSUE TITLE
drive pull panic

### ISSUE THREAD

**Issue by imozetic** [odeke-em/drive#875] opened 2017-02-06 10:46 UTC
> drive pull    results in the following errors:

Resolving...
panic: pgid (68719476737) above high water mark (18)

goroutine 1 [running]:
panic(0x7f0117faf320, 0xc4203fae50)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/boltdb/bolt.(*node).spill(0xc4201730a0, 0xc4203e01a0, 0xc4203e01a0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/node.go:375 +0x616
github.com/boltdb/bolt.(*node).spill(0xc420173030, 0x10, 0x10)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/node.go:350 +0xb7
github.com/boltdb/bolt.(*Bucket).spill(0xc4202ac7f8, 0x7f011cf1f6c6, 0x7f01184d69e0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/bucket.go:570 +0x43b
github.com/boltdb/bolt.(*Tx).Commit(0xc4202ac7e0, 0x0, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/tx.go:163 +0x125
github.com/boltdb/bolt.(*DB).Update(0xc4201321e0, 0x7f01180bbd30, 0x0, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/boltdb/bolt/db.go:605 +0x10d
github.com/odeke-em/drive/config.(*Context).CreateIndicesBucket(0xc420015080, 0x0, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/config/config.go:255 +0xaf
github.com/odeke-em/drive/config.(*Context).DeserializeIndex(0xc420015080, 0xc42042b5a0, 0x1c, 0x0, 0x0, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/config/config.go:115 +0x64
github.com/odeke-em/drive/src.(*Commands).deserializeIndex(0xc420015100, 0xc42042b5a0, 0x1c, 0xc4201a3978)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/push.go:244 +0x42
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.deserializeIndex)-fm(0xc42042b5a0, 0x1c, 0x7f0117fa24a0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/changes.go:719 +0x3e
github.com/odeke-em/drive/src.resolveConflicts(0xc42049a300, 0x20, 0x20, 0xc42049a200, 0xc4201a3a90, 0x20, 0xc42049a300, 0x20, 0x20, 0x7f0117bf7ae5, ...)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/changes.go:700 +0x104
github.com/odeke-em/drive/src.(*Commands).resolveConflicts(0xc420015100, 0xc42044ea00, 0x3d, 0x40, 0x0, 0x0, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/changes.go:719 +0x1c0
github.com/odeke-em/drive/src.pull(0xc420015100, 0x2, 0x0, 0x0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/pull.go:117 +0x2e0
github.com/odeke-em/drive/src.(*Commands).Pull(0xc420015100, 0xc42000ae00, 0xc420015100)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/src/pull.go:71 +0x34
main.(*pullCmd).Run(0xc4200dc2d0, 0xc42000c370, 0x0, 0x0, 0xc4201840c0)
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/cmd/drive/main.go:797 +0x9cd
github.com/odeke-em/command.Run()
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/command/command.go:202 +0x81
github.com/odeke-em/command.ParseAndRun()
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
	/build/drive-Qo5puD/drive-0.3.9.1/src/github.com/odeke-em/drive/cmd/drive/main.go:126 +0x1968

**Comment by odeke-em** [comment] 2017-02-07 03:53
Hello there @imozetic, thanks for the issue and welcome to drive!

This issue is a duplicate of https://github.com/odeke-em/drive/issues/824.

**Closed by odeke-em** 2017-02-07 03:53 UTC
