### ISSUE TITLE
drive pub presents an invalid public address of Google Docs + Sheets.

### ISSUE THREAD

**Issue by dgvirtual** [odeke-em/drive#73] opened 2015-02-27 15:06 UTC
Great program with a hopeful potential! 

When I try to publish a google document using drive pub command, the document gets shared publically, but the drive pub command returns an invalid address for the published document. 

Here:

me@mine:~/Drive$ drive pub test
/test Published on https://googledrive.com/host/1nR2ZzEe6XqjEUVqeQdRkI3OqzR2lI5PQhzlBgixkbS8

If you press the link, you will end up with a 404 error. 

through the web interface one can find the real address of the publically shared document, it is this in this case: 

https://docs.google.com/document/d/1nR2ZzEe6XqjEUVqeQdRkI3OqzR2lI5PQhzlBgixkbS8/edit?usp=sharing

You can see that the ID part of the document is the same, but the rest of the address is wrong.

It may be because I use my own domain (google apps account?),  I have not checked it with the regular google account.

It is also to be noted that there are two ways make a document public in Google Documents. One is called Publishing (to be found under the File menu) and it produces a non-editable version. The other is called sharing, and accessible via a special button on the top right corner. There are various modes of sharing, one of which makes the document public, but it stays a Google Documents document all the same. I expected that "pub" option, in contrast with "share" option, will publish document in the first sense, but I got the second. Not a big problem, imho, but maybe it could be rearranged to more exactly align with the google apps behaviour?

**Comment by odeke-em** [comment] 2015-02-27 15:12
Thank you for reporting this. To get started, did you check out `drive share`? Also the fileId in both cases looks uniform so that eliminates the variable of invalid fileId. Makes me suspect the domain.

**Comment by odeke-em** [comment] 2015-02-27 15:19
To test out a hypothesis I have about Google Docs, would you mind publishing a non Google doc? E.g a photo, then a folder -- different mimeTypes.

**Comment by odeke-em** [comment] 2015-02-27 16:32
Been able to reproduce this, it confirms my suspicions about Google Docs + Sheets using a different publicView domain. I'll jump onto this in about 10 hours when I get back home.

**Comment by dgvirtual** [comment] 2015-02-27 16:36
Thank you for a quick response. By the way, I am currently using drive version 0.1.0, but this problem has been present before.

Strange: 
$ drive pub test.png 
/test.png Published on https://googledrive.com/host/0B7N4UaoQWBXiY1ZKamR1c09hMHM

- The above address works.

$ drive pub testdir/
/testdir Published on https://googledrive.com/host/0B7N4UaoQWBXiUS1CcE9EYmw0STQ

- The directory publishing also works!

Now, the sharing thing: 
I also did some tests, as you suggested.

$ drive share -emails dgvirtual@gmail.com -message "Test of Share feature" -role writer -type group test_shared.png 
Message:
         Test of Share feature
Receipients:
        + dgvirtual@gmail.com

File(s) to share:
        + test_shared.png
Proceed with the changes? [Y/n]: Y
googleapi: Error 500: Internal Error, internalError

Ok, strange... The command actually failed, the file did not get shared. Also it fails the same way repeatedly, and inbetween other commands do work, so it is not a temporary issue.

It is also to be noted that when I did the command this way after reading help: 

$ drive share test_shared.png -emails="dgvirtual@gmail.com" -message="testing share feature of drive" -notify=true -role="writer"

It just failed (the file was not shared) without any messages being printed on the command prompt.

Anything else I can do to test this out?

**Comment by odeke-em** [comment] 2015-02-27 16:43
Thank you for the tests, as mentioned above the issue is with Google Docs + Sheets using a different publishing domain. It seems like a change in Google Docs + Sheets in the last year or so ie them supplying a generated URL instead of allowing for access through the usual domain: sometime back I reported a bug to the Google Drive team in which created Doc files right after upload to your drive, before they were converted and had their url changed to point to the Google Docs domain, you'd get that error. I could be wrong about the Google Drive bug but so far it points to the pub url for Docs + Sheets.

**Comment by dgvirtual** [comment] 2015-02-27 18:41
When I removed the "-type group" part from the command, it completed successfully (the file was successfully shared with my other account): 

$ drive share -emails dgvirtual@gmail.com -message "Test of Share feature" -role writer test_shared.png 
Message:
         Test of Share feature
Receipients:
        + dgvirtual@gmail.com

File(s) to share:
        + test_shared.png
Proceed with the changes? [Y/n]: Y 

Actually, I have not explored the particulars of the share command and the possibilities that google gives for sharing, I do not even know what "-type group"  means. :)

**Comment by odeke-em** [comment] 2015-02-28 19:23
Fixed by https://github.com/odeke-em/drive/commit/7140805e858d3a0f8ebc57c594766a3363da6d58

**Closed by odeke-em** 2015-02-28 19:23 UTC
