### ISSUE TITLE
Renaming a file and pushing ... 200%

### ISSUE THREAD

**Issue by malteseunderdog** [odeke-em/drive#765] opened 2016-10-12 15:06 UTC
``````
xxx@yyy:~/gdrive$ drive push docs
Resolving...
- /docs/xwrf/2016/receipts/microsoft_office265home.pdf
+ /docs/xwrf/2016/receipts/microsoft_office365home.pdf
Deletion count 1 dest: 61.12KB
Addition count 1 src: 61.12KB
Proceed with the changes? [Y/n]:Y
 125168 / 62584 [======================================================] 200.00% 4s```
``````

**Comment by canpolat** [comment] 2016-11-06 13:59
Duplicate of #177

**Comment by odeke-em** [comment] 2016-11-07 05:36
Thanks @malteseunderdog and @canpolat, yeah this is a duplicate. It is high time that I fixed that issue. Jumping on it soon.

**Closed by odeke-em** 2016-11-07 05:36 UTC

**Comment by odeke-em** [comment] 2016-11-07 06:28
Thanks for the patience, fixed by PR https://github.com/odeke-em/drive/pull/784.

Please get the latest from master by
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
