### ISSUE TITLE
pull with -matches and -ignore-name-clashes

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#389] opened 2015-09-24 01:53 UTC
While using these flags, I try and re-try to download a folder from Google Drive:

`~/GoogleDrive/Pictures $ ls *Zagreb*`
`ls: cannot access *Zagreb*: No such file or directory`

`~/GoogleDrive/Pictures $ drive pull -ignore-name-clashes -matches *zagreb*`

```
~/GoogleDrive/Pictures $ drive pull -ignore-name-clashes -matches *zagreb*
+ /Zagreb, Aug 26-31, 2015/IMG_3531.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3493.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3490.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3484.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3526.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3487.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3495.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3478.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3483.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3524.JPG
(more files).......
Addition count 85 src: 194.01MB
Modification count 4 src: 5.88MB dest: 5.88MB
Proceed with the changes? [Y/n]:y
209591397 / 209591397 [========================================] 100.00 % 1m10s
```
`~/GoogleDrive/Pictures $ ls *Zagreb*`
`ls: cannot access *Zagreb*: No such file or directory`

I will try this command again and one more time and I get the same result. On the 2nd and 3rd try, some files have the 'modified' flag on them, some still have the addition '+' flag.

`~/GoogleDrive/Pictures $ drive version`
`drive version: 0.2.9`
`Commit Hash: '39bf5c6934116d5cedb6414dc9dce6adfef51fc6'`
`Go Version: go1.4`
`OS: linux/386`
`BuildTime: 2015-09-23 22:59:54.363760903 -0300 ADT`

What can I do to debug this?

**Comment by odeke-em** [comment] 2015-09-24 09:46
Hello @ikwyl6, sorry for the late reply, assignments had me busy :)

Hmm, that's an interesting case, so your Zagreb, * directory is in the root i.e `~/GoogleDrive` instead of `~/GoogleDrive/Pictures`.
this is from
```shell
+ /Zagreb, Aug 26-31, 2015/IMG_3531.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3493.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3490.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3484.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3526.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3487.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3495.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3478.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3483.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3524.JPG
````

with paths relative to the pseudo-root ie "/".

Also if you recall, `--matches` does prefix matches.

In regards to `--ignore-name-clashes`, I've always advised against using it since it just greedily gets the first available path and uses that -- I'd rather the user sees the conflict then renames these files. drive supports renaming `drive rename ....`.
The `--ignore-name-clashes` option exists because, despite the understanding that clashing same names in the same path won't be allowed by your file system, yet are allowed by Google Drive, users still want to use drive in these cases. Currently this is the solution until some form of clashes handling is introduced locally :(

Please let me know what you find. Also great catch with `--matches`, I think you might have found a bug(that could be a feature) because following the normal logic, the matches are supposed to be relative to the current directory, not the root.

**Comment by ikwyl6** [comment] 2015-09-24 10:05
@odeke-em yes you are correct. My Zagreb folder was placed in the root directory locally but exists in GoogleDrive/Pictures remotely. 
I never noticed this when trying to find it. 

Let me know if you need more info from me.

**Comment by odeke-em** [comment] 2015-09-24 10:16
@ikwyl6 thanks for the response. I'll probably jump on this in the next few days between breaks and mos def on the weekend. Good stuff raising it! Am off to bed, catch you in a bit.

**Comment by ikwyl6** [comment] 2015-09-24 10:40
And I think -matches should be relative to the current path and not how it works now (root), as you've mentioned above.

**Comment by odeke-em** [comment] 2015-09-24 16:19
Hello @ikwyl6 I just got sometime and fixed a bug that isn't directly related to yours, but is related to matches, with PR https://github.com/odeke-em/drive/pull/391. Please get the latest.
Now in regards to pulling folder `Zagreb,*`, I couldn't reproduce that, are you sure that was the exact location of the folder ie in Pictures? If so or even not, you can verify the existance by trying a `drive list --matches Zagreb`
Please get the latest and try this again and then let me know. Thanks.

**Comment by ikwyl6** [comment] 2015-09-24 22:24
Before downloading the current:
`~/GoogleDrive/Pictures $ drive list --matches Zagreb` gives the correct result:

`/Pictures/Zagreb, XXX, Aug 30, 2015/IMG_3282.JPG`
`/Pictures/Zagreb, XXX, Aug 30, 2015/IMG_3284.JPG`
`(more files)...`

`~/GoogleDrive/Pictures $ drive version`
`drive version: 0.2.9`
`Commit Hash: '60133cfe2e539f4e913505606cb75bf8f3caa4e8'`
`Go Version: go1.4`
`OS: linux/386`
`BuildTime: 2015-09-24 19:18:12.991524212 -0300 ADT`

`~/GoogleDrive/Pictures $ drive pull -ignore-name-clashes -matches *zagreb*`
`These 1 file(s) would be overwritten. Use -ignore-conflict to override this behaviour`
`X /Zagreb, XXX, Aug 30, 2015/IMG_3288.JPG 0ByyAgauS8QS_U0Q4SXVwUHZoN3c`
`conflicts have prevented a pull operation`

Although there is a conflict (which is new compared to last time this command was run), it is still showing this folder at the root and not at `$ROOT/Pictures`.

**Comment by odeke-em** [comment] 2015-09-25 03:51
The odd thing though is that I tried rebuilding your hierarchy this morning and run a couple of tests during my break, but couldn't get it to pull to root. I'll try again later.

**Comment by odeke-em** [comment] 2015-10-04 05:32
Ping! Please try reproducing this.

**Comment by ikwyl6** [comment] 2015-10-08 02:21
Producing same result..... The folders are being placed in the root.

```
$ drive version
drive version: 0.2.9
Commit Hash: '60133cfe2e539f4e913505606cb75bf8f3caa4e8'
Go Version: go1.4
OS: linux/386
BuildTime: 2015-10-07 22:46:51.468665081 -0300 ADT
```
```
~/GoogleDrive/Pictures $ drive pull -matches Zagreb
clashes detected. use `ignore-name-clashes` to override this behavior
```
```
~/GoogleDrive/Pictures $ drive pull -ignore-name-clashes -matches Zagreb 
These 1 file(s) would be overwritten. Use -ignore-conflict to override this behaviour
X /Zagreb, A and D Wedding, Aug 30, 2015/IMG_3288.JPG 0ByyAgauS8QS_U0Q4SXVwUHZoN3c
conflicts have prevented a pull operation
```
```
~/GoogleDrive/Pictures $ drive pull -ignore-conflict -matches Zagreb 
clashes detected. use `ignore-name-clashes` to override this behavior
```
```
~/GoogleDrive/Pictures $ drive pull -ignore-conflict -ignore-name-clashes -matches Zagreb
+ /Zagreb, A and D Wedding, Aug 30, 2015/IMG_3482.JPG
+ /Zagreb, A and D Wedding, Aug 30, 2015/IMG_3523.JPG
+ /Zagreb, A and D Wedding, Aug 30, 2015/IMG_3588.JPG
+ /Zagreb, A and D Wedding, Aug 30, 2015/IMG_3586.JPG
+ /Zagreb, A and D Wedding, Aug 30, 2015/IMG_3587.JPG
+ /Zagreb, A and D Wedding, Aug 30, 2015/IMG_3589.JPG
X /Zagreb, A and D Wedding, Aug 30, 2015/IMG_3288.JPG
+ /Zagreb, A and D Wedding, Aug 30, 2015/IMG_3287.JPG
.....(more files)...
+ /Zagreb, Aug 26-31, 2015
+ /Zagreb, Aug 26-31, 2015/IMG_3531.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3292.JPG
+ /Zagreb, Aug 26-31, 2015/IMG_3493.JPG
.....(more files)...
Addition count 404 src: 748.41MB
Clashing modification count 1 src: 1.29MB dest: 896.76KB
Proceed with the changes? [Y/n]:    
786119200 / 786119200 [========================================] 100.00 % 15m21s
```
```
~/GoogleDrive/Pictures $ ls *Zagreb*
ls: cannot access *Zagreb*: No such file or directory
~/GoogleDrive/Pictures $ ls -d ../*Zagreb*
../Zagreb, A and D Wedding, Aug 30, 2015  ../Zagreb, Aug 26-31, 2015
```
```
~/GoogleDrive/Pictures $ drive list -matches zagreb
/Pictures/Zagreb, A and D Wedding, Aug 30, 2015/IMG_3482.JPG 
/Pictures/Zagreb, A and D Wedding, Aug 30, 2015/IMG_3523.JPG 
/Pictures/Zagreb, A and D Wedding, Aug 30, 2015/IMG_3588.JPG 
.....(more files)...
/Pictures/Zagreb, Aug 26-31, 2015/IMG_3531.JPG 
/Pictures/Zagreb, Aug 26-31, 2015/IMG_3493.JPG 
/Pictures/Zagreb, Aug 26-31, 2015/IMG_3490.JPG 
/Pictures/Zagreb, Aug 26-31, 2015/IMG_3484.JPG 
.....(more files)...
```

**Comment by ikwyl6** [comment] 2015-10-08 02:40
Any `drive pull -matches $SEARCH_TERM` I do will try to download files/folders as "new" as drive doesn't see this $SEARCH_TERM that matches folders in `~/GoogleDrive/` but they actually exist in `~/GoogleDrive/Pictures/`

**Comment by odeke-em** [comment] 2015-10-08 02:43
Thanks for that info. I'll collect some more info from you over the weekend and as my previous trial to reproduce it failed. Also you are a bunch of commits behind, v0.3.1 will be released in a few days ;)

**Comment by ikwyl6** [comment] 2015-10-08 09:36
I did a go update & drive-gen literally right before I commented on this. Strange.

**Comment by odeke-em** [comment] 2015-10-08 17:16
Not quite ;) The right way that t README also shows is
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by odeke-em** [comment] 2015-10-11 03:32
Hello @ikwyl6 thanks for the patience, I was finally able to reproduce and diagnose the bug you reported. Thanks for reporting it. I've addressed it with PR https://github.com/odeke-em/drive/pull/430 and if you get the latest from master, it should be fixed!

**Closed** 2015-10-11 03:32 UTC
Labels: bug
