### ISSUE TITLE
gopath/src/github.com/odeke-em/drive/cmd/drive/main.go:33: syntax error: unexpected string literal, expecting comma or )

### ISSUE THREAD

**Issue by erlansonc** [odeke-em/drive#860] opened 2017-01-25 02:39 UTC
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/chris/gopath"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

Running on Linux Mint 18.1 64 bit using 4.4.0-53-generic kernel

When I run:
CGO_ENABLED=0 go get -u github.com/odeke-em/drive/cmd/drive

I get:
github.com/odeke-em/drive/cmd/drive
gopath/src/github.com/odeke-em/drive/cmd/drive/main.go:33: syntax error: unexpected string literal, expecting comma or )

I installed:  golang git mercurial  build-essential

Any ideas?
Thanks

**Comment by shaggytwodope** [comment] 2017-01-25 03:13
So this is a dupe of #852 among other issues opened. What you can do is upgrade to go 1.7. Or you can use the ppa, which I assume would work for mint. The ppa is running the latest code base currently. And is always updated asap.

**Comment by odeke-em** [comment] 2017-01-27 07:36
Hello there @erlansonc, welcome to drive!

Yap yap, as @shaggytwodope mentioned and recommended, this issue is a duplicate of #852, please get go1.7.

**Closed by odeke-em** 2017-01-27 07:36 UTC
