### ISSUE TITLE
panic: assertion failed: write: circular dependency occurred

### ISSUE THREAD

**Issue by wsnoble** [odeke-em/drive#861] opened 2017-01-25 16:55 UTC
I tried pushing a large directory structure with this command:

drive push -ignore-checksum=false -quiet 2012-fdr-psm

It yielded the error

panic: assertion failed: write: circular dependency occurred

goroutine 1131507 [running]:
panic(0x8a7240, 0xc503d00850)
	/net/noble/vol1/home/noble/software/go/src/runtime/panic.go:500 +0x1a1
github.com/boltdb/bolt._assert(0xc529535100, 0x97fabe, 0x23, 0x0, 0x0, 0x0)
	/net/noble/vol1/home/noble/work/src/github.com/boltdb/bolt/db.go:1029 +0xff
..

I am running 

bash-4.1$ drive version
drive version: 0.3.9.1
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 

My OS is CentOS Release 6.8 with linux kernel 2.6.32.

Full output log is attached.

[drive.txt](https://github.com/odeke-em/drive/files/730370/drive.txt)

**Comment by wsnoble** [comment] 2017-01-25 17:00
Follow-up: Removing the "-ignore-checksum" flag gets rid of the error.

**Comment by odeke-em** [comment] 2017-01-27 07:41
Hello there @wsnoble, thank you for the issue and welcome to drive!

So  for the past 1 month or so, we've been plagued by such boltdb crashes but
excluding `-ignore-checksum` is a first, thanks for trying that.


There are a few issues similar to this one:
* https://github.com/odeke-em/drive/issues/607
* https://github.com/odeke-em/drive/issues/846

and a wiki entry was made here https://github.com/odeke-em/drive/wiki/Boltdb-breaks-drive-with-(panic:-invalid-page-type:)-or-(panic:--above-high-water-mark).
Please take a look at the wiki entry and see if that does anything for you.

**Comment by wsnoble** [comment] 2017-01-27 15:19
I'm trying this boltdb solution but got stuck after I did

$ cd $GOPATH/src/github.com/boltdb/bolt && git reset --hard
852d3024fa8d89dcc9a715bab6f4dcd7d59577dd

That seemed to work fine (it said "HEAD is now at 852d302 skip empty pages
during cursor seek"). However, the command "drive-gen" that I'm supposed to
issue next does not seem to exist on my system. Is that supposed to be
alongside "drive" in $GOPATH/bin?

Sorry if this is not the right place to ask this. I don't see any way to
post a query to Aaron Nel on that wiki.

Bill



On Thu, Jan 26, 2017 at 11:41 PM, Emmanuel T Odeke <notifications@github.com

**Comment by odeke-em** [comment] 2017-01-27 18:08
@wsnoble thanks for trying it out.
drive-gen can be got by running
```shell
$ go get -u github.com/odeke-em/drive/drive-gen
```

and then it should be available in your $GOPATH/bin

**Comment by wsnoble** [comment] 2017-01-30 20:53
OK, that worked. But I still get an error:

panic: page 2 already freed

goroutine 1127304 [running]:
panic(0x8a7240, 0xc511a0a630)
	/net/noble/vol1/home/noble/software/go/src/runtime/panic.go:500 +0x1a1
github.com/boltdb/bolt.(*freelist).free(0xc511a0c390, 0x23, 0x7ffbb418c000)
	/net/noble/vol1/home/noble/work/src/github.com/boltdb/bolt/freelist.go:121 +0x2c0

Is there anything else I might try, or further debug information that you would find useful?

Bill
[drive.txt](https://github.com/odeke-em/drive/files/740252/drive.txt)

**Comment by odeke-em** [comment] 2017-02-03 05:39
Hey @wsnoble, please get and test out with the latest boltdb as per https://github.com/boltdb/bolt/pull/654
You can do so by running
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
and let me know if the problem persists and I'll report back to the boltdb issue.

**Comment by wsnoble** [comment] 2017-02-04 08:06
I did this, but I get the same problem.  Attached is a log showing the output when I issued the command you suggested, followed by the panic message issued from my push command.
[drive.txt](https://github.com/odeke-em/drive/files/752112/drive.txt)

**Comment by odeke-em** [comment] 2017-02-04 08:14
Ah crap, sorry that you've had so much trouble getting it to work. Let me cross-compile a binary for you from my computer.

**Comment by odeke-em** [comment] 2017-02-04 08:24
Please see https://drive.google.com/open?id=0By5qQkvRAeV2aGh5Ukt1Tm9zZnc
or below
```
$ cat md5-v0.3.9.1.txt 
$ md5 drive_linux 
MD5 (drive_linux) = a63ea02ab301371c8e102af2b88bfd7c
URL: https://drive.google.com/open?id=0By5qQkvRAeV2RHFubnd2NE1GNGM
```

**Comment by wsnoble** [comment] 2017-02-04 16:08
Alas! Your binary also fails, with an identical error (attached).  :(
[drive.txt](https://github.com/odeke-em/drive/files/752370/drive.txt)

**Comment by odeke-em** [comment] 2017-02-07 03:58
Thanks @wsnoble for the report. Perhaps this is connected to the OS treatment by
Go's runtime of CentOS and how boltdb behaves, as the same code works alright on OSX but
the cross-compiled binary fails.
Also this issue is a duplicate of https://github.com/odeke-em/drive/issues/846.

**Closed by odeke-em** 2017-02-07 03:58 UTC
