### ISSUE TITLE
Older mtime files not being pushed

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#104] opened 2015-03-16 23:25 UTC
Version `$ drive version
drive version 0.1.3`

1) I copied older files (unix timestamped in 2013) from one directory (outside of google drive root) to a folder within my google drive root, $GD/Documents/SOME_PATH1/SOME_PATH2 using a desktop file manager. SOME_PATH2 has been previously pushed to Google Drive before these files were copied.
2) Open command line: `drive push` from within SOME_PATH2:

```
$ drive push SOME_PATH2
Resolving...
These 1 file(s) would be overwritten. Use -ignore-conflict to override this behaviour
/Documents/SOME_PATH1/SOME_PATH2/new doc.pdf
```
but there have been more files than just "new doc.pdf" copied to this directory. `drive diff` from within this directory gives me 5-6 files that differ, that are only on local:

But running:
`drive diff` gives:
```
* remote:         2014-12-28T14:03:14.000Z                
* local:          2013-04-13T00:52:14.000Z                
********************************************************************************
FILE.file1
********************************************************************************
* remote:         2014-12-28T14:01:36.000Z                
* local:          2013-04-13T00:52:17.000Z                
********************************************************************************
FILE.file2
********************************************************************************
********************************************************************************
FILE.file2 only on remote
********************************************************************************
FILE.file3 only on remote
* remote:         2013-03-10T21:35:28.000Z                
* local:          2013-03-10T21:35:15.000Z                
********************************************************************************
FILE.file4 only on local
********************************************************************************
FILE.file5 only on local
********************************************************************************
FILE.file6 only on local
********************************************************************************
FILE.file7 only on local
********************************************************************************
FILE.file8 only on local
********************************************************************************
FILE.file9 only on local
********************************************************************************
FILE.file10 only on local
********************************************************************************
FILE.file11 only on local
```
The files above that have different remote and local timestamps are not the issue, it is the "only on local" files that are not being pushed.

Upon further inspection, I think this is from timestamped files not being newer than the most recent file in the target directory since the last push. IE: The files I copied into these directories above are timestamped as 2013 and drive is not picking this up. They are new files to the SOME_PATH2 directory but they are not seen by drive.

`drive stat FILE.file9`
` /Documents/SOME_PATH1/SOME_PATH2/FILE.file9: remote path doesn't exist`

A `drive list` shows files that are not present locally on my machine.

**Comment by odeke-em** [comment] 2015-03-16 23:44
drive is meant to be used inside the root that it was mounted. It does a greedy search for the .gd directory and the first that it finds is what it uses. This behaviour might vary across commands because they interprete arguments different. However, it still remains that drive should be run inside the specific root.

**Comment by ikwyl6** [comment] 2015-03-17 00:25
Ok fair enough. But my "update" at the bottom should be a new bug. I ran drive push from within the directory and it still did not pick up on the older time stamp, copied  files. I will update the title.

**Comment by odeke-em** [comment] 2015-03-17 00:26
To be honest, this does not provide enough information to even debug it. Did you do a drive stat, drive list, to actually confirm that you have these files?

**Comment by ikwyl6** [comment] 2015-03-17 00:33
As per above, locally I have these files. I checked web version of google drive, I do not have these files. Forget the "drive push" outside of GD_ROOT for now, that point is obsolete but my "UPDATE" should be the description of this bug. I'm on mobile and will edit title after. 

If you need stat and list I can provide. I though the diff output above was enough. My problem is they are not pushed from local to google drive. The unix mtime on the file (locally) is 2013 but I've pushed this directory in 2015. The "2013" files were copied just today and have kept the 2013 mtime on the file. Drive is not picking up these newly copied files.

**Comment by odeke-em** [comment] 2015-03-17 00:37
The logs would be ideal. Also I'd rather close this issue and open something else or see if there is such an issue present. Otherwise there will be too much noise in this issue in case folks are looking at it.

**Comment by CountryBumkin** [comment] 2015-03-17 00:51
lkwyl wrote... Drive is not picking up these newly copied files. 

Could be issue #38 ??

**Comment by odeke-em** [comment] 2015-03-17 00:54
When performing operations, could you please perform them relative to the mounted root? In that issue #38 no one has yet produced any leads such as where they were running drive from, what happened, any suspiscions, a detailed log. It is almost guess work that I doing for that issue without this kind of information.

**Comment by ikwyl6** [comment] 2015-03-17 01:01
For this issue I am running all commands from within the root.

**Comment by odeke-em** [comment] 2015-03-17 01:01
A log please :)

**Comment by ikwyl6** [comment] 2015-03-17 01:09
The log is above in the initial bug post. I renamed actual files to FILE.file1, 2, 3. 
The `drive push` above is the actual output... Everything in code blocks is actual output except for file names, I have renamed those.

**Comment by odeke-em** [comment] 2015-03-17 01:19
Thank you for that. However, if you look at your logs you will notice that you have NOT specified the relative path, ie `pwd` after the `cd`, which path are you running this? -- this gives clues as to what could be going on. Secondly you are still using the syntax from the old issue where you were performing operations such as diff-ing content outside of the drive mount point. Thirdly, I don't see the `ls` or even `ls -lthA` output to match up with the files. Also I do not see the `drive list` output nor `drive stat` output. `drive diff` is NOT sufficient as the log. I would recommend a step by step walk through, and in case you do not want to share the listings publicly you can email me a secret gist showing your step through. Otherwise this is really hard to reproduce or even debug. I have files from 2012 that I am able to push up with no problem. As many details about what is going on would be useful for folks to be able to help solve your issue. It is also a duplicate of #38 as @CountryBumkin mentioned before.

**Comment by ikwyl6** [comment] 2015-03-17 02:04
```
ikwyl6@ikwyl6-laptop:~/GoogleDrive/Documents/SOME_PATH1/SOME_PATH2$ ls -al
total 4324
drwxr-xr-x 2 ikwyl6 ikwyl6    4096 2015-03-16 22:38 .
drwxr-xr-x 9 ikwyl6 ikwyl6    4096 2015-03-10 22:49 ..
-rw-r--r-- 1 ikwyl6 ikwyl6  223661 2013-02-19 20:45 FILE.file1.pdf
-rw-r--r-- 1 ikwyl6 ikwyl6    9132 2013-04-12 21:52 FILE.file2.tax
-rw-r--r-- 1 ikwyl6 ikwyl6  228707 2013-04-12 21:52 FILE.file3.pdf
-rw-r--r-- 1 ikwyl6 ikwyl6       0 2015-03-16 22:38 FILE.file4.pdf
-rw-r--r-- 1 ikwyl6 ikwyl6  950007 2013-03-13 18:36 FILE.file5.pdf
-rw-r--r-- 1 ikwyl6 ikwyl6 1408122 2013-03-10 18:35 FILE.file6.pdf
-rw-r--r-- 1 ikwyl6 ikwyl6   82045 2013-03-10 18:32 FILE.file7.pdf
-rw-r--r-- 1 ikwyl6 ikwyl6   83182 2013-03-10 18:32 FILE.file8.pdf
-rw-r--r-- 1 ikwyl6 ikwyl6 1038015 2013-03-12 08:53 FILE.file9.pdf
-rw-r--r-- 1 ikwyl6 ikwyl6       0 2014-03-08 18:52 FILE.file10
-rw-r--r-- 1 ikwyl6 ikwyl6    9540 2013-03-15 11:58 FILE.file10.ods
-rw-r--r-- 1 ikwyl6 ikwyl6   56277 2013-03-15 12:03 FILE.file10.pdf
-rw-r--r-- 1 ikwyl6 ikwyl6    8595 2013-03-15 11:57 FILE.file10.xlsx
-rw-r--r-- 1 ikwyl6 ikwyl6   12272 2013-04-12 21:17 FILE.file11
-rw-r--r-- 1 ikwyl6 ikwyl6  283674 2013-04-12 21:09 FILE.file12
```

```
ikwyl6@ikwyl6-laptop:~/GoogleDrive/Documents/SOME_PATH1/SOME_PATH2$ drive list
/Documents/SOME_PATH1/SOME_PATH2/FILE.file2.tax
/Documents/SOME_PATH1/SOME_PATH2/FILE.file3.pdf
/Documents/SOME_PATH1/SOME_PATH2/FILE.file9.pdf
/Documents/SOME_PATH1/SOME_PATH2/FILE.file3.pdf
/Documents/SOME_PATH1/SOME_PATH2/FILE.file2.tax
/Documents/SOME_PATH1/SOME_PATH2/FILE.file4.pdf
/Documents/SOME_PATH1/SOME_PATH2/FILE.file5.pdf
/Documents/SOME_PATH1/SOME_PATH2/FILE.file5.pdf
/Documents/SOME_PATH1/SOME_PATH2/FILE.file6.pdf
/Documents/SOME_PATH1/SOME_PATH2/FILE.file7.pdf
/Documents/SOME_PATH1/SOME_PATH2/FILE.file1.pdf
```

```
ikwyl6@ikwyl6-laptop:~/GoogleDrive/Documents/SOME_PATH1/SOME_PATH2$ drive push
Resolving...
These 1 file(s) would be overwritten. Use -ignore-conflict to override this behaviour
/Documents/SOME_PATH1/SOME_PATH2/FILE.file6.pdf
$
```

```
ikwyl6@ikwyl6-laptop:~/GoogleDrive/Documents/SOME_PATH1/SOME_PATH2$ drive stat

/Documents/SOME_PATH1/SOME_PATH2
FileId               0ByyAgauS8QS_R0xlQmoxRnRhMnc  
Bytes                0                             
Size                 0.00B                         
DirType              folder                        
MimeType             application/vnd.google-apps.folder
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTQyNDkwNjg4MTc5MA"
ModTime              2015-02-25 23:28:02 +0000 UTC 

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*
```

**Comment by odeke-em** [comment] 2015-03-17 02:10
This is great! Thank you. One last thing: just like you did for:
 ```
ikwyl6@ikwyl6-laptop:~/GoogleDrive/Documents/SOME_PATH1/SOME_PATH2$ drive stat
```

Could you make it

```
drive stat -r
```

**Comment by ikwyl6** [comment] 2015-03-19 23:57
`ikwyl6@ikwyl6-laptop:~/GoogleDrive/Documents/SOME_PATH1$ drive stat -r SOME_PATH2`

```
/Documents/SOME_PATH1/SOME_PATH2
FileId               0ByyAgauS8QS_R0xlQmoxRnRhMnc  
Bytes                0                             
Size                 0.00B                         
DirType              folder                        
MimeType             application/vnd.google-apps.folder
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTQyNDkwNjg4MTc5MA"
ModTime              2015-02-25 23:28:02 +0000 UTC 

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

/Documents/SOME_PATH1/SOME_PATH2/FILE.file3.pdf
FileId               0ByyAgauS8QS_LTFZeEVWVkVXR3c  
Bytes                228707                        
Size                 223.35KB                      
DirType              file                          
MimeType             application/pdf               
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTQxOTc3NTI5NjQ2MQ"
ModTime              2014-12-28 14:01:36 +0000 UTC 
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTQxOTc3NTM5NDEwMw"
ModTime              2014-12-28 14:03:14 +0000 UTC 
Md5Checksum          7a0c011848fb3b410a68a82a2ddac6da

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

/Documents/SOME_PATH1/SOME_PATH2/FILE.file10
FileId               1g3cxq7NPXLXjnrDk8kOIi0v1QGq5-4sVD5lb6_PlW4Q
Bytes                0                             
Size                 0.00B                         
DirType              file                          
MimeType             application/vnd.google-apps.spreadsheet
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTM5NDMxOTE1NjE3NA"
ModTime              2014-03-08 22:52:36 +0000 UTC 
Md5Checksum                                        

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

*
Name: X1-WIFE X2 <x1wifex2@gmail.com>
Role                 writer                        
AccountType          user                          
*

/Documents/SOME_PATH1/SOME_PATH2/FILE.file3.pdf
FileId               0ByyAgauS8QS_N2NyMVc4VWwtbEE  
Bytes                228707                        
Size                 223.35KB                      
DirType              file                          
MimeType             application/pdf               
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTM2NTgxNDMzNjc4Mg"
ModTime              2013-04-13 00:52:17 +0000 UTC 
Md5Checksum          d76f0884595756e7e93a8ac50912f51b

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

/Documents/SOME_PATH1/SOME_PATH2/FILE.file2.tax
FileId               0ByyAgauS8QS_bXFJYlV2Nmw0b3M  
Bytes                9132                          
Size                 8.92KB                        
DirType              file                          
MimeType             text/xml                      
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTM2NTgxNDMzNDAyMQ"
ModTime              2013-04-13 00:52:14 +0000 UTC 
Md5Checksum          7a0c011848fb3b410a68a82a2ddac6da

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

/Documents/SOME_PATH1/SOME_PATH2/FILE.file5.pdf
FileId               0ByyAgauS8QS_YUZYdDV5OVNIQlE  
Bytes                950007                        
Size                 927.74KB                      
DirType              file                          
MimeType             application/pdf               
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTM2MzIxMDU4NjA0MQ"
ModTime              2013-03-13 21:36:26 +0000 UTC 
Md5Checksum          afe84cd6fe6f48907a44994ce477e944

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

/Documents/SOME_PATH1/SOME_PATH2/FILE.file6.pdf
FileId               18cWsHC6qf4ir8IciZpr5rue9WqbX47bBeQE9Nit4XPsXAZ2QkYaUhitWBnq2
Bytes                845320                        
Size                 825.51KB                      
DirType              file                          
MimeType             application/pdf               
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTM2Mjk1MTMyNzYxOQ"
ModTime              2013-03-10 21:35:28 +0000 UTC 
Md5Checksum          4d69011cbb902329c4f0809bca39b06f

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

/Documents/SOME_PATH1/SOME_PATH2/FILE.file6.pdf
FileId               1Avd_RO1SOD4JU8lWT8h2AGyWNlMM4hpngzAYX-WbImi0XxNu81okRuD89xuX
Bytes                1408122                       
Size                 1.34MB                        
DirType              file                          
MimeType             application/pdf               
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTM2Mjk1MTMxNDY2Mg"
ModTime              2013-03-10 21:35:15 +0000 UTC 
Md5Checksum          a2a9f18d3832aa192db30299cbd6e7ca

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

/Documents/SOME_PATH1/SOME_PATH2/FILE.file7.pdf
FileId               0ByyAgauS8QS_OHFTQ3E1cTI5MjA  
Bytes                82045                         
Size                 80.12KB                       
DirType              file                          
MimeType             application/pdf               
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTM2Mjk1MTE2NzkxMg"
ModTime              2013-03-10 21:32:48 +0000 UTC 
Md5Checksum          ef9c591a3c21d2f8fb9b838261a37575

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

/Documents/SOME_PATH1/SOME_PATH2/FILE.file8.pdf
FileId               0ByyAgauS8QS_S0x1bFE2UUJMdnM  
Bytes                83182                         
Size                 81.23KB                       
DirType              file                          
MimeType             application/pdf               
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTM2Mjk1MTE2NjAyNQ"
ModTime              2013-03-10 21:32:46 +0000 UTC 
Md5Checksum          ca3c4b73275d49e2566126ec1016dfc1

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*

/Documents/SOME_PATH1/SOME_PATH2/FILE.file1.pdf
FileId               0ByyAgauS8QS_Q2FjUjJiQ3FQR0E  
Bytes                223661                        
Size                 218.42KB                      
DirType              file                          
MimeType             application/pdf               
Etag                 "tlWfk03TbBHKoqyGbIYE6wA918U/MTM2MTMyMTEzMjE0Mg"
ModTime              2013-02-20 00:45:32 +0000 UTC 
Md5Checksum          33e77f2b07ad6519f6722b2c03f65d1f

*
Name: X1 X2 <ikwyl6@gmail.com>
Role                 owner                         
AccountType          user                          
*
```

**Comment by odeke-em** [comment] 2015-03-19 23:59
Okay, now as you can see you ALREADY have those files on your drive, you probably assumed that you did not have them.

**Comment by odeke-em** [comment] 2015-03-20 00:25
I am closing this issue since your files were already uploaded yet you assumed that they were not. The drive stat -r and drive list even show that the files were present. A conflict was detected and drive tried to avoid clobbering your data with file `/Documents/SOME_PATH1/SOME_PATH2/FILE.file6.pdf` hence the warning.

**Closed by odeke-em** 2015-03-20 00:25 UTC

**Comment by ikwyl6** [comment] 2015-03-20 01:31
?? Maybe i'm missing something here. A quick comparison of the "drive list" and my "ls -al" show a different in files not present on google drive. Where is:

File8
File10.xls
File10.ods
File10.pdf
File11
File12

On google drive? I am trying to do a push. 

Am I not seeing these files present and you are?

**Comment by odeke-em** [comment] 2015-03-20 02:14
Wait a second, it is not pushing to drive because you have a conflict. Have you resolved the conflict? If you don't care about the conflict, have you re-run `drive push --ignore-conflict`?

**Comment by ikwyl6** [comment] 2015-03-20 02:27
I know how to solve the conflict. Shouldn't it still show the conflict for one file but also confirm to push the others? My expectation would be Yes.

**Comment by odeke-em** [comment] 2015-03-20 02:32
Nope. I am all for fail if any conflict is detected. This way if someone is uploading thousands of files and something is wrong with the integrity of the file (modified in multiple places) it aborts and can actually find out which file exactly. Also running `--ignore-conflict` or `--force` should still show you the conflicted file but permit the operations. Remember we are playing it safe. For a quick reference around try pushing anything using git for which conflicts exist, it will abort, to avoid guesswork scenarios.

**Comment by odeke-em** [comment] 2015-03-20 02:51
@ikwyl6 also sorry I should have mentioned, you probably wanna reduct some of the output from drive list :)

**Comment by ikwyl6** [comment] 2015-03-20 03:02
I guess this whole thing stems from my expectation that it should still try to add and push ('+') the missing files to drive that are on my local directory, regardless of conflicts with other unrelated files. This is why I started the issue. I understand your logic. Thanks for the clarification. Perhaps as a suggestion you should add is a statement at the end of your "conflict" output to say "any further changes to other files have not been reviewed. Conflict needs to be addressed before proceeding" or something along those lines. Just a thought. Thanks

**Comment by odeke-em** [comment] 2015-03-20 03:05
That is a good suggestion actually, that I am going to add since it makes it clear to the user what the intention is. I totally agree that some people would want operations to proceed normally, I personally would prefer your expectation but I think playing it safe is better. In the future I will try to increase as much communication to the user where possible. Thank you for raising this.

**Comment by odeke-em** [comment] 2015-03-20 04:31
@ikwyl6 in a commit I just made ie https://github.com/odeke-em/drive/commit/f068c8ce4e7b559c7a84eecf78cdb3d824cc51aa I present more information in case of conflicts, as you had suggested. Hope this helps.
