### ISSUE TITLE
pull from nonexistent directory fails silently

### ISSUE THREAD

**Issue by theavey** [odeke-em/drive#959] opened 2017-10-04 20:21 UTC
If I try to pull a file that doesn't exist, I get an error:

    user $ drive pull nofile
    Resolving...
    '/gdrive/nofile' aka '/home/user/gdrive/nofile' doesn't exist locally nor remotely

If I try to pull from a directory that doesn't exist, I get no error:

    user $ drive pull nodir/nofile
    Resolving...
    Everything is up-to-date.

I might be missing something in the implications of this, but I would expect the same error in the second case.

**Comment by odeke-em** [comment] 2017-11-10 00:24
Hello there @theavey, thank you for the issue and welcome to drive! My apologies for the late reply, I have been swamped.

What version of drive are you using? I can't reproduce this issue
```shell
$ drive pull nodir
Resolving...
 | 
'/nodir' aka '/Users/emmanuelodeke/emm.odeke/nodir' doesn't exist locally nor remotely
$ drive pull nodir/foo
Resolving...
 \ 
'/nodir/foo' aka '/Users/emmanuelodeke/emm.odeke/nodir/foo' doesn't exist locally nor remotely
 drive version
drive version: 0.3.9.1
Commit Hash: '08ef171674e04babd8da74e52aa9fa9aebefbf1f'
Go Version: devel +0e9d293 Sun Jun 11 04:25:26 2017 +0000
OS: darwin/amd64
BuildTime: 2017-10-01 22:16:26.378669572 -0600 MDT m=+0.049346292
``` 

Please get the latest, rebuild and try again. I'll close this issue, please reopen if the latest code trips out.

**Closed by odeke-em** 2017-11-10 00:24 UTC
