### ISSUE TITLE
API authentification error when push several GBs

### ISSUE THREAD

**Issue by Issam2204** [odeke-em/drive#193] opened 2015-05-12 20:11 UTC
Hello! I'm having issues every time I try to push several GBs.

file_1.tar: googleapi: Error 401: Invalid Credentials, authError

The error doesn't interrupt the push action. However, the file in question is not uploaded.

My go version -->  go version go1.2.1 linux/amd64

Right now I started a push of 1.3TB (17299 files) which should end in one week. This could also be useful to test drive under heavy usage.

**Comment by Issam2204** [comment] 2015-05-13 10:38
I reached 22.3% (pushing 1.3TB).

So far I got 12 error 401, which means 12 skipped files from uploading.

**Comment by odeke-em** [comment] 2015-05-14 06:30
Hello again @Issam2204! Sorry for the late reply, I've been quite busy.
This issue is a duplicate of a couple of other issues, please take a look at the discussion here at https://github.com/odeke-em/drive/issues/116

**Comment by Issam2204** [comment] 2015-05-14 06:44
Thank you very much @odeke-em! 

And sirry for the duplicate :)

**Comment by odeke-em** [comment] 2015-05-14 06:46
No worries, sorry for the issue btw. If it helps, you could run say three instances of drive on distinct directories -- this is a very duct tape solution until solving the auto OAuth timeout refresh is in. Thanks for the patience.

**Comment by Issam2204** [comment] 2015-05-14 06:47
@odeke-em again thanks! I'll certainly do that :)

Have a nice one!

**Comment by odeke-em** [comment] 2015-05-14 07:29
Cheers!

**Closed by odeke-em** 2015-05-14 07:29 UTC
Labels: duplicate

**Comment by odeke-em** [comment] 2015-06-08 15:11
Hello again @Issam2204 btw this got fixed on master over the weekend.

**Comment by ikwyl6** [comment] 2015-06-14 22:00
Still happening with v 2.4.0
`googleapi: Error 401: Invalid Credentials, authError`

when doing a push for atleast an hour. I downloaded master today.

**Comment by odeke-em** [comment] 2015-08-06 04:39
Hey folks please get the latest from master by
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```
Uploading should be faster and there is also a mechanism for exponential backoff on encountering retryable errors.
