### ISSUE TITLE
Cannot push an object when its parent folder(s) do(es) not already exist online

### ISSUE THREAD

**Issue by jean-christophe-manciot** [odeke-em/drive#876] opened 2017-02-06 15:36 UTC
Ubuntu 16.10 4.8
drive 0.3.9.1
Commit Hash: '8c26f34b24e0e681acfaffee4149edbbd0aec6a2'
For instance, at this point, there is no Android folder online.
```
# object="Android/Nexus-5"
# drive push -force -depth 0 -no-prompt -hidden -verbose "$object" 2>&1
Resolving...
Everything is up-to-date.
```
Although:
```
# object="Android"
# drive push -force -depth 0 -no-prompt -hidden -verbose "$object" 2>&1
Resolving...
+ /Android
Addition count 1
Push::Started /Android
Push::Done /Android
# object="Android/Nexus-5"
# drive push -force -depth 0 -no-prompt -hidden -verbose "$object" 2>&1
Resolving...
+ /Android/Nexus-5
Addition count 1
Push::Started /Android/Nexus-5
Push::Done /Android/Nexus-5
```
Same remark with a file.
For instance, if I remove online the newly created Android and its descendant:
```
# object="Android/Nexus-5/Flash-Stock-Boot-System-Recovery-and-OTA.sh"
# drive push -force -no-prompt -hidden -verbose "$object" 2>&1
Resolving...
Everything is up-to-date.
```
Although:
```
# object="Android"
# drive push -force -depth 0 -no-prompt -hidden -verbose "$object" 2>&1
Resolving...
+ /Android
Addition count 1
Push::Started /Android
Push::Done /Android
# object="Android/Nexus-5"
# drive push -force -depth 0 -no-prompt -hidden -verbose "$object" 2>&1
Resolving...
+ /Android/Nexus-5
Addition count 1
Push::Started /Android/Nexus-5
Push::Done /Android/Nexus-5
# object="Android/Nexus-5/Flash-Stock-Boot-System-Recovery-and-OTA.sh"
# drive push -force -depth 0 -no-prompt -hidden -verbose "$object" 2>&1
Resolving...
+ /Android/Nexus-5/Flash-Stock-Boot-System-Recovery-and-OTA.sh
Addition count 1 src: 3.19KB
 0 / 3262 [---------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%Push::Started /Android/Nexus-5/Flash-Stock-Boot-System-Recovery-and-OTA.sh
 3262 / 3262 [===================================================================================================================================================] 100.00% 0sPush::Done /Android/Nexus-5/Flash-Stock-Boot-System-Recovery-and-OTA.sh
 3262 / 3262 [===================================================================================================================================================] 100.00% 1s
```
**drive should create all non existing parent folders when pushing any type of object (folder/file).**

**Comment by jean-christophe-manciot** [comment] 2017-02-06 15:38
Also, the drive message "Everything is up-to-date." is incorrect.

**Comment by odeke-em** [comment] 2017-02-07 03:42
Duplicate of https://github.com/odeke-em/drive/issues/848.

**Closed by odeke-em** 2017-02-07 03:42 UTC
