### ISSUE TITLE
Create a local copy of the upstream doc, beyond the link

### ISSUE THREAD

**Issue by alanfranz** [odeke-em/drive#335] opened 2015-08-10 09:44 UTC
This is one major nuisance (for me) of the official Google Drive client for Mac/Windows: I find on my disk only the link to online documents, not any file. So if I'm on the plane or any other place without internet access I cannot even read such files (there's an option for offline editing in Chrome but it works on a file-per-file basis AFAIK).

What I'd like is something like that: choose a format for documents (openoffice vs msoffice vs pdf), and along the link the client downloads a copy of the rendered document, marks it as readonly (to prevent accidental modifications) and never tries to sync it back, it effectively becomes a one-way local backup of the remote source. 

This would solve, at least partially, the issue.

I'm not sure if this can be done through the API, if it could be done I'll be happy to contribute.

**Comment by odeke-em** [comment] 2015-08-10 16:11
Hello @alanfranz. Welcome to drive and thank you for raising this issue!

So, you can already do `drive pull --explicitly-export --export pdf,doc,[otherformats...] --export-dir ~/my_exports <docs_to_export>`.

**Comment by alanfranz** [comment] 2015-08-13 09:48
This is interesting, but afaiu requires exporting in a different directory than the rest of the files, something that I don't love, since it creates some confusion.

I'll make you a proposal for a different behaviour when I get back from my vacation.

Thanks!

**Comment by odeke-em** [comment] 2015-08-14 08:14
Hello @alanfranz, you can export to the same directory. Sure, I can understand that.
However, my personal view is that exporting to the same directory creates way more confusion since all of a sudden you'll have new files every time, and you'll have to push them back up, I'd prefer to keep my drive clean -- but that's just my view.

**Comment by odeke-em** [comment] 2015-09-12 02:10
Ping!

**Comment by odeke-em** [comment] 2015-10-04 05:35
I'll be closing this issue since exporting of docs should be left to the user and there is quite a bit of complexity, confusion and clutter that could be caused by dropping doc file exports within the same dir.
Thanks for the discussion

**Closed by odeke-em** 2015-10-04 05:35 UTC
