### ISSUE TITLE
drive Md5 update issue

### ISSUE THREAD

**Issue by DenomZero** [odeke-em/drive#237] opened 2015-06-16 22:48 UTC
First off, awesome work.  This program gets better every time I check in on it.  I was on 0.1.0 so I've been playing with some of the new features.
     So the md5 checksum is a great idea.  I was going through the main page and saw the difference example
diff -y <(drive md5sum) <(md5sum *)
So I ran this, saw the differences and then did
drive push -ignore-conflict
Then I go back to 
diff -y <(drive md5sum) <(md5sum *)
and Its reporting the same differences.  So back to
drive push -ignore-conflict
Resolving...
Everything is up-to-date.

Hopefully I am using this correctly and not just having a big brain fart.  If so I'm sure its a small bug but could cause somebody some undue head scratching if they are setting up scripts etc.  Thanks again for the great app and keep up the good work.

**Comment by odeke-em** [comment] 2015-06-17 01:45
Hello @DenomZero, welcome to drive. Thank you for the kind words.
So with `--ignore-conflict` you are actually ignoring conflicts that might exist, would you mind repeating the example without `--ignore-conflict`?

**Comment by DenomZero** [comment] 2015-06-17 02:14
Id like to apologize in advance for the text formatting.  Its a direct copy from the terminal. 

diff <(drive md5sum) <(md5sum *)
md5sum: Work: Is a directory
2,3c2,3
< 08b77fe2cc80d31727fa6e719fab30ab  Notes.ctb
< 124f8844cf54b83960c5d7e4ac99c809  Notes.ctb~
---
> a24202bb90760bac887cb3b4052ebf90  Notes.ctb
> ba51065dcf4a07a152940f1e35904135  Notes.ctb~

----------------------------------------------------------------------------

drive push 
Resolving...
M /Documents/Notes.ctb~
M /Documents/Notes.ctb
Modification count 2 src: 230.00KB dest: 230.00KB
Proceed with the changes? [Y/n]:y
235520 / 235520 [===============================================================================================] 100.00 % 1s

-----------------------------------------------------------------------

diff <(drive md5sum) <(md5sum *)
md5sum: Work: Is a directory
2,3c2,3
< 08b77fe2cc80d31727fa6e719fab30ab  Notes.ctb
< 124f8844cf54b83960c5d7e4ac99c809  Notes.ctb~
---
> a24202bb90760bac887cb3b4052ebf90  Notes.ctb
> ba51065dcf4a07a152940f1e35904135  Notes.ctb~

**Comment by odeke-em** [comment] 2015-06-17 03:17
I can't seem to reproduce this issue, sure that swap file isn't being modifed quite a bit. Also since after the second push you no longer have changes, makes me think that it might just be the noise from different depth traversals and encountering directories by md5sum.
Here might be something to cut down the noise:
Okay, so `md5sum` works on files and not directories. However `drive md5sum` will traverse folders present remotely as deep as the default ie 1. You can control the traversal depth like this
`drive diff --depth <n>` where n is an integer

As you can see from your warnings md5sum tries to traverse a dir. You can cut out all this noise by level traversals and comparisons of something wild like
```shell
$ function differ() { if [[ $# -lt 2 ]]; then echo "<dir> <depth>";return;fi;dir=$1;depth=$2;diff <(drive md5sum --depth $depth $dir) <(md5sum $(find $dir -maxdepth $depth -type f));}
$ differ . 2 # Now you can use this differ function
```

In the future I plan on making drive self contained because right now the diff with md5sum example's right hand only works on Linux, on OS X md5 behaves differently. Also that would cut out all the fiddling and error prone typing.

**Comment by arniotis** [comment] 2015-06-19 16:42
@DenomZero are you certain that the push works? If you push twice in a row, does the second push report "Everything is up to date"?

**Comment by odeke-em** [comment] 2015-07-02 06:26
Ping @DenomZero

**Comment by odeke-em** [comment] 2015-07-14 04:51
Closing this issue as it seems more like a usage problem. Re-open if persists.

**Closed by odeke-em** 2015-07-14 04:51 UTC

**Comment by DenomZero** [comment] 2015-07-17 00:42
Ok this isnt really an md5 issue so much as it is an update issue.  I use CherryTree to make notes so it's modified regularly.
To recreate the issue with cherry tree first create a new doc and put some test data into it.  Save it as sqlite unprotected file, push it, great.  I leave cherry tree open this whole time.  Modify the document with more test data example Tree->Insert todays node and then more test data, then save.  Push the data.  Looks good, because it says it worked.  Close cherry tree and force pull the data.  Open your test document and the modifications are gone.  Im sure this is why the md5 checksum isnt jiving but I am unable to get the push to work on this file a 2nd time, I always just assumed it was working.  
Sorry for the long delay I dont have the most free time.  It might be worth moving this to a new issue as the md5 helped me find this issue.
