### ISSUE TITLE
Drive push missing some files

### ISSUE THREAD

**Issue by CountryBumkin** [odeke-em/drive#38] opened 2015-01-08 05:14 UTC
I was suspicious that a push of a new directory tree was missing some files so here is a detailed test.
I deleted all files and emptied the trash of my Google drive and deleted all files from my local path and made a new tree with a single top level and some sub directories. When the first push was complete I made a remote listing and then pushed the same folders again and 3 more files were required. Examination of the logs and listing showed the 3 files were not included in the first push logs.

All the details here... http://pastebin.com/taC9qkxi

Drive 0.0.4b from the Ubuntu ppa on Linux Mint 17.1 64bit.

**Comment by odeke-em** [comment] 2015-01-08 05:16
To be clear did you list them with a maximum depth of -1?

**Comment by CountryBumkin** [comment] 2015-01-08 05:17
This is the list command I used...
drive list -no-prompt -m=4 Test11 > ~gdbom1.txt

**Comment by odeke-em** [comment] 2015-01-08 05:18
Gotcha. Btw what files are missing, what do you expect?

**Comment by CountryBumkin** [comment] 2015-01-08 05:20
The 3 files missing are shown in the log of the second push, they are present in the ls listing but missing from the first push log and also the first remote listing. All is correct after the second push.

**Comment by odeke-em** [comment] 2015-01-08 05:22
Ah gotcha, sorry for that I hadn't noticed the bottom log. Thank you for the report, I'll try to reproduce this and fix it.

**Comment by mattlbaker** [comment] 2015-01-10 16:35
I have this same issue.  Here are steps to easily reproduce.

1. create a directory locally that does not exist in google drive.
2. put a bunch of files in it
3. start the push to google drive, but don't proceed with the changes
4. repeat step 3 several times.

Now you should be able to compare the output of pushing but not proceeding with the changes.  Here is my results below.  You can see that each push would have resulted in different numbers of files being sent to google drive.

```
[mlbaker@localhost drive]$ drive push pictures/
<REMOVED CONTENT>
Addition count 2590 src: 738.96MB
Proceed with the changes? [Y/n]: n
[mlbaker@localhost drive]$ drive push pictures/
<REMOVED CONTENT>
Addition count 2997 src: 764.87MB
Proceed with the changes? [Y/n]: n
[mlbaker@localhost drive]$ drive push pictures/
<REMOVED CONTENT>
Addition count 2706 src: 714.26MB
Proceed with the changes? [Y/n]: n
[mlbaker@localhost drive]$ drive push pictures/
<REMOVED CONTENT>
Addition count 2808 src: 773.51MB
Proceed with the changes? [Y/n]: n
[mlbaker@localhost drive]$ 
```

**Comment by CountryBumkin** [comment] 2015-01-20 02:58
I have been using drive version 0.0.6 from the PPA to push groups of files a few directories at a time. After several successful groups several files were 'discovered' in an earlier directory. It seems there is still a circumstance for missing files. Commands were like this, Google drive is mounted in Gdata.

 drive push -r -no-prompt -no-clobber /home/zzz/Gdata
Resolving...
[32m+[0m /Pictures/2008-11-30--14.45.26/100_1839.JPG  **  Previously Missed files
[32m+[0m /Pictures/2008-11-30--14.45.26/100_1838.JPG  **
[32m+[0m /Pictures/2008-11-30--14.45.26/100_1846.JPG  **
[32m+[0m /Pictures/2008-11-30--14.45.26/100_1856.JPG  **
[32m+[0m /Pictures/2009-05-29--18.35.50
[32m+[0m /Pictures/2009-05-29--18.35.50/100_1882.JPG
+ 50 more files that are new

**Comment by odeke-em** [comment] 2015-01-27 13:49
Couldn't reproduce this. Please try again and help me check if this persists.

**Comment by CountryBumkin** [comment] 2015-01-29 04:54
I have been doing more testing and the problem persists, recursive pushing in batches of about 50 files will miss some about 1 in 3 pushes - drive version 0.0.7 latest from the PPA. The local file tree and the remote drive are reserved only for testing and not accessed by any other software.
Checking the missed file properties reveals no special attributes, it has included some of sequentially numbered images for example.

It is not unusual for obscure system differences to produce unrepeatable bugs. Is it worth a debug command with options to highlight different sections of code which prints lots of details. The user captures this into a file, reviews for privacy, then emails it (possibly compressed) off to an email address you create for the purpose, then post an alert on the issue board.

PS: With the rapid progress the 'drive help command' text has lost the link to the 'drive command -h' detailed syntax list.

**Comment by odeke-em** [comment] 2015-01-29 05:02
README, or `drive command -h`?

**Comment by CountryBumkin** [comment] 2015-01-29 05:06
The help text from the drive program for example the 'drive help push' displayed text maks no reference to the availability of 'drive push -h' detailed syntax options.
eg....

zzz@Cooli7 ~ $ drive help push
Name
	push - push local changes to Google Drive
Description
	Uploads content to your Google Drive from your local path
	Push comes in a couple of flavors
		* Ordinary push: `drive push path1 path2 path3`
		* Mounted push: `drive push -m path1 [path2 path3] drive_context_path`
	
Note: You can skip checksum verification by using `-ignore-checksum`

zzz@Cooli7 ~ $ drive push -h
Usage of drive push:
  -convert=false: toggles conversion of the file to its appropriate Google Doc format
  -force=false: forces a push even if no changes present
  -hidden=false: allows pushing of hidden paths
  -ignore-checksum=false: avoids computation of checksums as a final checkin case for example you are low on bandwidth

**Comment by odeke-em** [comment] 2015-01-29 05:09
Feel free to submit a PR for the help if you'd like. In regards to some files missing, probably some hidden bug somewhere but otherwise I cannot reproduce this :(

**Comment by CountryBumkin** [comment] 2015-01-29 05:17
Considering the diversity of Linux system configurations unreproducible bugs will not be unusual which is why i suggested a systematic approach for detailed reporting.

In my case it wanted drive for remote backup and it is hard to trust this when it silently misses files.  
Consider also what could happen if the missing file was a directory ?

**Comment by odeke-em** [comment] 2015-01-29 05:22
Oh btw did you take a look at issue #50 or PR #51 ? The issue was a reproducible case for missing files that were nested in dirs non-existant on remote and hence they got skipped. Too bad for your frustrations, the tool is still maturing (28th day of transfer) so hopefully these issues will get nailed out. For sure, I am all ears for proposals for systematic approaches for detailed reporting.

**Comment by CountryBumkin** [comment] 2015-01-29 05:55
I have seen the error '<nil> remote path doesn't exist' many tests ago, but for new tests I delete everything on  the remote drive and the drive software is responsible for creating all remote directories and files, this attempts to limit the complexity from different versions and historical corruption of data.

**Comment by tomtor** [comment] 2015-02-22 08:45
0.1.0 still has this problem:

Initial push:

drive push S3 MemCard
...
Addition count 2725 src: 7.00GB

I get 8 errors during the push:
Error 401: Invalid Credentials, authError

Second push to verify transfer:
Addition count 51 src: 186.94MB

After this second push the directory tree is completely synced

**Comment by odeke-em** [comment] 2015-02-22 08:49
@tomtor  could it be because the push took a long time? an authError is at times caused when it takes long to complete a push, I think your error is more related to #53.

**Comment by tomtor** [comment] 2015-02-22 09:19
@odeke-em I get 8 authErrors, but miss 51 files?

**Comment by odeke-em** [comment] 2015-02-22 10:21
With a preceding error, so far no retry mechanism is present. I'll be adding a retry mechanism and exponential back off soon to handle such.

**Comment by odeke-em** [comment] 2015-07-03 03:33
Ping!

**Comment by CountryBumkin** [comment] 2015-07-03 04:01
I am not running drive routinely at present, I will need to update some scripts over the next few days to resume operation.

This was posted to #160 without clear resolution

-------------------------------------------------------------
After the drive pull command completed I immediately executed another drive pull command, just to check if drive would find any missing files that weren't downloaded the first time.
I would expect that drive would download nothing, because everything should be downloaded on the first drive pull command.

Unfortunately the second execution of the drive pull command found a lot of files to add and even files to modify ...and also files to delete. The files that were listed to be deleted are also listed to be added.
.........

------------------------------------------------------------

Regards CB

**Comment by odeke-em** [comment] 2015-07-03 04:03
Please test it again when you get a chance and then we can close this if it is solved.
Thank you.

**Comment by CountryBumkin** [comment] 2015-07-08 10:46
I have setup drive to run daily in a script file, this is a summary of events...
System - Linux Mint 17.1 64 bit, drive 0.2.5 from the PPA
I cleared Gdrive before starting, there was no other activity in Gdrive except for the drive pushes.
There was no activity in my host folders except the deliberate additions of data to push.

I pushed using this command
drive push -r -no-prompt -no-clobber /home/zzz/Gdata
I do this drive list command before and after each push.
drive list -r -version --sort name

The first push of about 120 small test files in 3 folders went normally.
The next push accurately reported 'Everything is up-to-date'
I added a folder of 61 jpg images.
This seemed to push normally but this progress display log was not helpful to identify which files are moving.
131584 / 44251459  0.30 % 19m0s
164352 / 44251459  0.37 % 16m6s
262656 / 44251459  0.59 % 10m36s
328192 / 44251459  0.74 % 9m49s
393728 / 44251459  0.89 % 9m17s
426496 / 44251459  0.96 % 9m35s
....

However every day this is now reported.
Resolving...
clashes detected. use `ignore-name-clashes` to override this behavior
I logged into Gdrive with a web browser and  the activity log only has entries for when files were actually pushed. The clash seems to be duplication of the image folder 2008-10-24--17.19.02 containing 5 images in one and the remainder in another copy.

I tried this in a terminal window
zzz@Cooli7 ~/Gdata $ drive push -r -no-prompt -no-clobber -ignore-name-clashes /home/zzz/Gdata
Resolving...
4265595 / 4265595 [===============================================] 100.00 % 52s

When I went back to Gdrive in the browser all 61 images were listed as created at the the time of the terminal command. The 61 images take 44Mb and the time taken to push is inconsistent with uploading this quantity. Just the files 00001.jpg to 00005.jpg were added. 

Listing of image files as first pushed... Note duplication of 2008-10-24 folder.
/Pictures  v42968
/test1  v42583
/Pictures/2008-10-24--17.19.02  v42987
/Pictures/2008-10-24--17.19.02  v42970
/Pictures/2008-10-24--17.19.02/00006.jpg  v42990
/Pictures/2008-10-24--17.19.02/00007.jpg  v42993
/Pictures/2008-10-24--17.19.02/00008.jpg  v42996
/Pictures/2008-10-24--17.19.02/00009.jpg  v42999
/Pictures/2008-10-24--17.19.02/00010.jpg  v43002
/Pictures/2008-10-24--17.19.02/00011.jpg  v43005
/Pictures/2008-10-24--17.19.02/00012.jpg  v43008
/Pictures/2008-10-24--17.19.02/00013.jpg  v43011
/Pictures/2008-10-24--17.19.02/00014.jpg  v43014
/Pictures/2008-10-24--17.19.02/00015.jpg  v43017
/Pictures/2008-10-24--17.19.02/00016.jpg  v43020
/Pictures/2008-10-24--17.19.02/00017.jpg  v43023
/Pictures/2008-10-24--17.19.02/00018.jpg  v43026
/Pictures/2008-10-24--17.19.02/00019.jpg  v43029
/Pictures/2008-10-24--17.19.02/00020.jpg  v43032
/Pictures/2008-10-24--17.19.02/00021.jpg  v43035
/Pictures/2008-10-24--17.19.02/00022.jpg  v43038
/Pictures/2008-10-24--17.19.02/00023.jpg  v43041
/Pictures/2008-10-24--17.19.02/00024.jpg  v43044
/Pictures/2008-10-24--17.19.02/00025.jpg  v43047
/Pictures/2008-10-24--17.19.02/00026.jpg  v43050
/Pictures/2008-10-24--17.19.02/00027.jpg  v43053
/Pictures/2008-10-24--17.19.02/00028.jpg  v43056
/Pictures/2008-10-24--17.19.02/00029.jpg  v43059
/Pictures/2008-10-24--17.19.02/00030.jpg  v43062
/Pictures/2008-10-24--17.19.02/00031.jpg  v43065
/Pictures/2008-10-24--17.19.02/00032.jpg  v43068
/Pictures/2008-10-24--17.19.02/00033.jpg  v43071
/Pictures/2008-10-24--17.19.02/00034.jpg  v43074
/Pictures/2008-10-24--17.19.02/00035.jpg  v43077
/Pictures/2008-10-24--17.19.02/00036.jpg  v43080
/Pictures/2008-10-24--17.19.02/00037.jpg  v43083
/Pictures/2008-10-24--17.19.02/00038.jpg  v43086
/Pictures/2008-10-24--17.19.02/00039.jpg  v43089
/Pictures/2008-10-24--17.19.02/00040.jpg  v43092
/Pictures/2008-10-24--17.19.02/00041.jpg  v43095
/Pictures/2008-10-24--17.19.02/00042.jpg  v43098
/Pictures/2008-10-24--17.19.02/00043.jpg  v43101
/Pictures/2008-10-24--17.19.02/00044.jpg  v43104
/Pictures/2008-10-24--17.19.02/00045.jpg  v43107
/Pictures/2008-10-24--17.19.02/00046.jpg  v43110
/Pictures/2008-10-24--17.19.02/00047.jpg  v43113
/Pictures/2008-10-24--17.19.02/00048.jpg  v43116
/Pictures/2008-10-24--17.19.02/00049.jpg  v43119
/Pictures/2008-10-24--17.19.02/00050.jpg  v43122
/Pictures/2008-10-24--17.19.02/00051.jpg  v43125
/Pictures/2008-10-24--17.19.02/00052.jpg  v43128
/Pictures/2008-10-24--17.19.02/clock.jpg  v43155
/Pictures/2008-10-24--17.19.02/CoolD Culvert.jpg  v43131
/Pictures/2008-10-24--17.19.02/CoolD Spillway.jpg  v43134
/Pictures/2008-10-24--17.19.02/CoolDam1.jpg  v43137
/Pictures/2008-10-24--17.19.02/CoolDam2.jpg  v43140
/Pictures/2008-10-24--17.19.02/Rock Culvert.jpg  v43143
/Pictures/2008-10-24--17.19.02/Rock Culvert2.jpg  v43146
/Pictures/2008-10-24--17.19.02/Rock Pool.jpg  v43149
/Pictures/2008-10-24--17.19.02/T41_psu.jpg  v43152
/Pictures/2008-10-24--17.19.02/00001.jpg  v42973
/Pictures/2008-10-24--17.19.02/00002.jpg  v42976
/Pictures/2008-10-24--17.19.02/00003.jpg  v42979
/Pictures/2008-10-24--17.19.02/00004.jpg  v42982
/Pictures/2008-10-24--17.19.02/00005.jpg  v42985

After terminal push command... Note the addition of files 00001.jpg to 00005.jpg.
/Pictures  v43203
/test1  v42583
/Pictures/2008-10-24--17.19.02  v43202
/Pictures/2008-10-24--17.19.02  v43200
/Pictures/2008-10-24--17.19.02/00001.jpg  v43178
/Pictures/2008-10-24--17.19.02/00002.jpg  v43181
/Pictures/2008-10-24--17.19.02/00003.jpg  v43184
/Pictures/2008-10-24--17.19.02/00004.jpg  v43187
/Pictures/2008-10-24--17.19.02/00005.jpg  v43190
/Pictures/2008-10-24--17.19.02/00006.jpg  v42990
/Pictures/2008-10-24--17.19.02/00007.jpg  v42993
/Pictures/2008-10-24--17.19.02/00008.jpg  v42996
/Pictures/2008-10-24--17.19.02/00009.jpg  v42999
/Pictures/2008-10-24--17.19.02/00010.jpg  v43002
/Pictures/2008-10-24--17.19.02/00011.jpg  v43005
/Pictures/2008-10-24--17.19.02/00012.jpg  v43008
/Pictures/2008-10-24--17.19.02/00013.jpg  v43011
/Pictures/2008-10-24--17.19.02/00014.jpg  v43014
/Pictures/2008-10-24--17.19.02/00015.jpg  v43017
/Pictures/2008-10-24--17.19.02/00016.jpg  v43020
/Pictures/2008-10-24--17.19.02/00017.jpg  v43023
/Pictures/2008-10-24--17.19.02/00018.jpg  v43026
/Pictures/2008-10-24--17.19.02/00019.jpg  v43029
/Pictures/2008-10-24--17.19.02/00020.jpg  v43032
/Pictures/2008-10-24--17.19.02/00021.jpg  v43035
/Pictures/2008-10-24--17.19.02/00022.jpg  v43038
/Pictures/2008-10-24--17.19.02/00023.jpg  v43041
/Pictures/2008-10-24--17.19.02/00024.jpg  v43044
/Pictures/2008-10-24--17.19.02/00025.jpg  v43047
/Pictures/2008-10-24--17.19.02/00026.jpg  v43050
/Pictures/2008-10-24--17.19.02/00027.jpg  v43053
/Pictures/2008-10-24--17.19.02/00028.jpg  v43056
/Pictures/2008-10-24--17.19.02/00029.jpg  v43059
/Pictures/2008-10-24--17.19.02/00030.jpg  v43062
/Pictures/2008-10-24--17.19.02/00031.jpg  v43065
/Pictures/2008-10-24--17.19.02/00032.jpg  v43068
/Pictures/2008-10-24--17.19.02/00033.jpg  v43071
/Pictures/2008-10-24--17.19.02/00034.jpg  v43074
/Pictures/2008-10-24--17.19.02/00035.jpg  v43077
/Pictures/2008-10-24--17.19.02/00036.jpg  v43080
/Pictures/2008-10-24--17.19.02/00037.jpg  v43083
/Pictures/2008-10-24--17.19.02/00038.jpg  v43086
/Pictures/2008-10-24--17.19.02/00039.jpg  v43089
/Pictures/2008-10-24--17.19.02/00040.jpg  v43092
/Pictures/2008-10-24--17.19.02/00041.jpg  v43095
/Pictures/2008-10-24--17.19.02/00042.jpg  v43098
/Pictures/2008-10-24--17.19.02/00043.jpg  v43101
/Pictures/2008-10-24--17.19.02/00044.jpg  v43104
/Pictures/2008-10-24--17.19.02/00045.jpg  v43107
/Pictures/2008-10-24--17.19.02/00046.jpg  v43110
/Pictures/2008-10-24--17.19.02/00047.jpg  v43113
/Pictures/2008-10-24--17.19.02/00048.jpg  v43116
/Pictures/2008-10-24--17.19.02/00049.jpg  v43119
/Pictures/2008-10-24--17.19.02/00050.jpg  v43122
/Pictures/2008-10-24--17.19.02/00051.jpg  v43125
/Pictures/2008-10-24--17.19.02/00052.jpg  v43128
/Pictures/2008-10-24--17.19.02/clock.jpg  v43155
/Pictures/2008-10-24--17.19.02/CoolD Culvert.jpg  v43131
/Pictures/2008-10-24--17.19.02/CoolD Spillway.jpg  v43134
/Pictures/2008-10-24--17.19.02/CoolDam1.jpg  v43137
/Pictures/2008-10-24--17.19.02/CoolDam2.jpg  v43140
/Pictures/2008-10-24--17.19.02/Rock Culvert.jpg  v43143
/Pictures/2008-10-24--17.19.02/Rock Culvert2.jpg  v43146
/Pictures/2008-10-24--17.19.02/Rock Pool.jpg  v43149
/Pictures/2008-10-24--17.19.02/T41_psu.jpg  v43152
/Pictures/2008-10-24--17.19.02/00001.jpg  v42973
/Pictures/2008-10-24--17.19.02/00002.jpg  v42976
/Pictures/2008-10-24--17.19.02/00003.jpg  v42979
/Pictures/2008-10-24--17.19.02/00004.jpg  v42982
/Pictures/2008-10-24--17.19.02/00005.jpg  v42985

regards CB

**Comment by odeke-em** [comment] 2015-07-08 16:48
Thank you for this experiment and for the results.
So the original issue isn't producible? The duplication is an issue that is still open and is still under investigation.

**Comment by odeke-em** [comment] 2015-07-14 04:55
Closing this issue. Please get the latest from master, re-open if persists.

**Closed by odeke-em** 2015-07-14 04:55 UTC
