### ISSUE TITLE
Progress bar over 100%

### ISSUE THREAD

**Issue by vankessel** [odeke-em/drive#669] opened 2016-06-16 17:34 UTC
The bar appears to be calculated by:

( amount_added + amount_deleted ) / total_to_be_added

So if there is an equal amount of additions and deletions it will go to around 200%

**Comment by odeke-em** [comment] 2016-06-17 09:05
Hello there @vankessel, thanks for creating this issue and welcome to drive.

I think this issue is a duplicate of https://github.com/odeke-em/drive/issues/177. Let's move the discussion there.

**Comment by odeke-em** [comment] 2016-07-12 01:23
Migrated to https://github.com/odeke-em/drive/issues/177.

**Closed by odeke-em** 2016-07-12 01:23 UTC

**Comment by odeke-em** [comment] 2016-11-07 06:29
Thanks for the patience, fixed by PR https://github.com/odeke-em/drive/pull/784.

Please get the latest from master by
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
