### ISSUE TITLE
localDelete removing index for: "X" at "Y" fileId for index must be non-empty

### ISSUE THREAD

**Issue by cdown** [odeke-em/drive#275] opened 2015-07-08 19:08 UTC
I moved two files using the Android mobile app from `/Authentication` to `/Authentication/Old passports`, and when I `drive pull`ed, these warnings appeared:

    localDelete removing index for: "Passport (compressed).pdf" at "/home/chris/Google Drive/Authentication/Passport (compressed).pdf" fileId for index must be non-empty
    localDelete removing index for: "Passport.pdf" at "/home/chris/Google Drive/Authentication/Passport.pdf" fileId for index must be non-empty

It does seem like it did the right thing -- ie. after `drive pull`, those files did get deleted from their old location and appeared at their new location, but the warnings seemed concerning.

**Comment by odeke-em** [comment] 2015-07-08 19:11
Hello @cdown thank you for reporting this and welcome to drive!
If I may ask, what does `drive version` say?
If it gets you template-ish information, please make sure to have run `go get github.com/odeke-em/drive/drive-gen && drive-gen` to bundle in the commit hash information, os information and Go version. After that then re-run `drive version`.

**Comment by odeke-em** [comment] 2015-07-08 19:19
Btw, I'll try to reproduce this when I get back home in about 5 hours.

**Comment by cdown** [comment] 2015-07-08 19:20
Sorry, I totally should have included that, my bad.

    drive version: 0.2.5
    Commit Hash: '14fcfb4fa6a22b1070176aa5e7c5a1c5bb40eddc'
    Go Version: go1.4.2
    OS: linux/amd64

**Comment by odeke-em** [comment] 2015-07-08 19:26
Thanks, I'll dive into this in ~5 hours when I am back home.

**Comment by cdown** [comment] 2015-07-08 19:43
No worries! I think this is lowpri since it does seem it does the right thing anyway.

**Comment by odeke-em** [comment] 2015-07-10 05:37
@cdown thank you for your patience, yesterday I got back home then went out asap and on getting back forgot about it. However, the issue is fixed please see PR https://github.com/odeke-em/drive/pull/278 and the latest in master should have the code merged in.

**Comment by odeke-em** [comment] 2015-07-10 05:38
Please re-open if it persists.

**Closed by odeke-em** 2015-07-10 05:38 UTC
Labels: bug

**Comment by cdown** [comment] 2015-07-10 08:36
Thanks a lot for the speedy resolution! (y)

**Comment by odeke-em** [comment] 2015-07-10 08:37
Thank you for reporting this issue. You actually found a bug that was going to annoy a whole lot of users :)
