### ISSUE TITLE
Strange behavior on first usage

### ISSUE THREAD

**Issue by arnuschky** [odeke-em/drive#43] opened 2015-01-13 11:51 UTC
Not sure how to call or report this issue. I am trying to use drive for the first time, and it doesn't really behave in a confidence-inducing way:

I call `drive init` followed by `drive pull`. So far so good, I end up with a directory that holds all my files. If I now call `drive push` without changing anything, I get a long list of modified and deleted files! Some files are even listed twice, once as modified and once as deleted. Obviously, I am *very* reluctant to call `drive push` as I fear it will delete the listed files (more than 100) irrevocably from by google drive. 

What is going wrong here?

**Comment by odeke-em** [comment] 2015-01-13 13:13
What version of drive?

**Comment by arnuschky** [comment] 2015-01-13 13:27
version         0.0.4d

**Comment by odeke-em** [comment] 2015-01-13 13:55
I've tried reproducing this issue on version 0.0.4d as well as the latest 0.0.5, using two different Google Drive accounts and failed to. One account with about 88 files, the other with about 1192 files
Let's try to diagnose the problem. Anything special about these paths, urls, etc? Duplicate file names?

**Comment by arnuschky** [comment] 2015-01-13 16:53
You were right, I managed to eliminate the majority of the conflicts by removing duplicates. Some of them weren't duplicates at all but just two different files with the same name. Even though I read the warning in the docs before using it, this seems to be a major source of data loss. Maybe `drive` could at least warn about the issue?

Now, regarding the other files that show up as modified: most of those seem to be Google maps and Google forms files, that recently turned up on my Google drive. I can't seem to remove them (or at least, they re-appear). Google must have recently decided to store these things on Google drive... A little bit annoying as they clutter my root folder. Nonetheless, why do these show up in `drive` as modified?

Then there are a few files that are stored in a folder that includes a slash (Artwork/Websites). This gets translated into Artwork%2FWebsites on my filesystem. No idea why these show up partially as modified, and partially as deleted (or both).

Finally, I have 3 files (all in the same dir) that show up as modified and that do not have any special name or duplicates.

**Comment by odeke-em** [comment] 2015-01-13 17:02
In about 9 hours when I am back from work I can break it down for you as well as help solve a whole bunch of them. For starters please use the latest from master, I actually tackled the 'Artwork/Websites' since *NIX file systems use '/' as the path separator files with such fields create conflicts with directories hence that gets combated by url encoding the path and saving it as is, then on cloud comparison, reconverts it, the latest from master should have no issues with such. Also the Google maps and Google forms, I'll handle in the next few commits. In deed a warning could be given but then again that will entail breaking the current flow for which the current users are made aware of. Psst there is a mode called '-no-clobber' usable with pull/push that should prevent deletions/modifications just in case you have lots of duplicate files. Also you can use your forms and Google Docs by exporting them.
Please let me know what your thoughts are on this, and if there any other issues.

**Comment by arnuschky** [comment] 2015-01-13 17:37
I used `go get -u github.com/odeke-em/drive/cmd/drive` as indicated in the readme to install `drive`. I assumed that this installs master.

**Comment by odeke-em** [comment] 2015-01-14 01:07
That should get you the latest. See before you said your version was 0.0.4d yet the latest is 0.0.5.

**Comment by arnuschky** [comment] 2015-01-14 01:48
Weird, I now go 0.0.5. I must have installed it before you released the new version, I guess.

**Comment by odeke-em** [comment] 2015-01-14 02:34
No biggie, feel free to close this issue once all is well and please don't hestitate to reach out in case of any questions.

**Comment by arnuschky** [comment] 2015-01-14 11:04
Actually, apart the maps and forms, I still have some files that are marked as modified when I call `pull` or `push`.

A bunch of them seemed to be buggy: the website told me that the file type is unknown and the file is of zero size. However, it was able to show a preview (these files were spreadsheets). Weird. As they were old, I zapped them.

Which leaves one file: it's a PDF without special naming (`/Sport/Frisbee/farewell party.pdf`), I can download it and view it without problems.

**Comment by arnuschky** [comment] 2015-01-14 11:04
BTW, thank you for all your patience with my issues here. :)

**Comment by odeke-em** [comment] 2015-01-15 09:05
No worries, am glad to be of help. Thank you for using drive as well as the responding during the diagnosis. In the future you can use the `no-clobber` option for push/pull in case you don't want to have to remove duplicate/conflicting files. This will only do additions, every other operation is ignored. Then you can selectively pull or push on the files you want later on if you decide to delete or modify the duplicates.

**Closed** 2015-01-15 17:53 UTC
