### ISSUE TITLE
drive does weird things on 5xx HTTP responses when pulling

### ISSUE THREAD

**Issue by cdown** [odeke-em/drive#734] opened 2016-09-14 13:08 UTC
When trying to pull I got this:

```
% drive pull
Resolving...                                                                                                                                        
+ XXX.pdf
+ YYY.pdf
Addition count 2 src: 77.37MB
Proceed with the changes? [Y/n]:y
 0 / 81128125 [--------------------------------------------------------------------------------------------------------------------------------------]   0.00%
pull: /XXX.pdf err: download: failed for url "https://googledrive.com/host/<redacted>". StatusCode: 502
 81064099 / 81128125 [============================================================================================================================]  99.92% 4s
% echo $?
0
% ls -l XXX.pdf
-rw-r--r-- 1 chris chris 0 Sep 14 15:01 XXX.pdf
% file XXX.pdf
XXX.pdf: empty
```

Two weird things here:

1. `drive` returns exit code 0 even when it got a 5xx during pull
2. `drive` creates an empty file for the errored file. This seems bad since it creates the illusion that the file was successfully copied

```
% drive version
drive version: 0.3.7
Commit Hash: 'bd7e3f5ad5a67a27892e47da5c36452bfdfb8513'
Go Version: go1.6.2
OS: linux/amd64
BuildTime: 2016-06-11 19:52:06.74253692 +0100 BST
```

**Comment by dermesser** [comment] 2016-09-14 17:26
Hey there, I'm working on Drive (but not here in my employer's mission). tl;dr: Drive Web Hosting, which provides the https://googledrive.com/host/... urls is being turned down. The recommended path forward is to use the API's download method.

I created #735 , and highly recommend that it is merged soon, as the official deprecation date has already passed (https://support.google.com/drive/answer/2881970?hl=en)

**Comment by odeke-em** [comment] 2016-09-14 18:03
@cdown thank you for the issue, definitely a bug.

@dermesser found the cause of it for starters https://github.com/odeke-em/drive/issues/734#issuecomment-247090606, and made a patch to fix it https://github.com/odeke-em/drive/pull/735.

Please get the latest from master.

**Comment by cdown** [comment] 2016-09-14 18:06
This solves the "intentional 502" situation, but not the actual issue that occurs on 500s, no? Maybe I'm missing something, though.

**Comment by dermesser** [comment] 2016-09-14 18:08
@cdown, you're correct. This won't solve the actual handling of errors.

**Comment by odeke-em** [comment] 2016-09-14 18:35
@cdown, yes in deed, for starters this helps mask the problem that led you to discover that errors on download aren't being handled alright. Your issue still stands, that's why I haven't yet closed it.

**Closed** 2016-09-15 04:24 UTC
Labels: bug

**Comment by odeke-em** [comment] 2016-09-15 04:26
@cdown thank you for reporting this issue. I've addressed it with https://github.com/odeke-em/drive/pull/737. Please get the latest from master.

Also thanks @dermesser for covering the first bases.

**Comment by yottabit42** [comment] 2016-09-20 01:34
I just pulled from master as I had just encountered the StatusCode 502 error.

Upon restarting my pull, the client appears to be pulling all files again instead of only pulling the changes.

`Clashing modification count 12 src: 113.38MB
Deletion count 8 dest: 9.03MB
Addition count 15774 src: 31.77GB`

**Comment by yottabit42** [comment] 2016-09-20 01:55
And then after that pull finished:

> 34215725118 / 34229412077 [======================================================================================================================================================================]  99.96% 56m32s

/Google Photos/2015/06/IMG_6786.JPG err: googleapi: got HTTP response code 503 with body: Service Unavailable

/Google Photos/2013/09/IMG_1732.JPG err: googleapi: got HTTP response code 500 with body: {
 "error": {   "errors": [    {     "domain": "global",
    "reason": "internalError",     "message": "Internal Error"    }   ],
  "code": 500,   "message": "Internal Error"  } }  
/Google Photos/2013/09/IMG_2686.JPG err: googleapi: got HTTP response code 500 with body: {
 "error": {   "errors": [    {     "domain": "global",
    "reason": "internalError",     "message": "Internal Error"    }   ],
  "code": 500,   "message": "Internal Error"  } }  
/Google Photos/2013/07/2013-07-31 19_09_22.jpg err: unexpected EOF 
/Google Photos/2012/06/IMG_5485.JPG err: unexpected EOF 
/Google Photos/2009/08/IMG_8764.jpg err: unexpected EOF 
/Google Photos/2009/01/CIMG1962.JPG err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2001/09/09060114_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2001/09/09100002_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2001/09/09070020_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2001/08/08250074_G.jpg err: unexpected EOF 
/Google Photos/2001/08/08240079_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2001/07/07030030_G-edited.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2001/03/03310033_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2000/12/12260001_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2000/12/12230005_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2000/10/10270002_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2000/10/10110018_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2000/08/08240010_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2000/08/08250005_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }  
/Google Photos/2000/06/06270063_G.jpg err: googleapi: got HTTP response code 500 with body: {
 "error": {   "code": 500,   "message": null  } }

**Comment by odeke-em** [comment] 2016-10-03 07:27
@yottabit42 this is kind of weird, seems like that 503 at the beginning caused it to trip more hence the 500s. Unfortunately, I don't have any insights for why we'll be getting those 500s as they are on Google Drive's backend :(
