### ISSUE TITLE
Uploading docx and odt files creates compressed archives in google drive web app

### ISSUE THREAD

**Issue by jnazaroff** [odeke-em/drive#154] opened 2015-04-22 00:40 UTC
I used drive push to upload some docs I was working on,, and when I went to the official web app, this is what I saw:
![problem](https://cloud.githubusercontent.com/assets/12055474/7265313/847ea1cc-e84c-11e4-8b72-07381b1cbeb2.jpg)

I tried double-clicking it, and I got this:
![problem2](https://cloud.githubusercontent.com/assets/12055474/7265367/3d174194-e84d-11e4-9c15-76201b610fad.jpg)

Anyone else had this issue before?  What is going on?  How can i change it (if there is an option already)?

EDIT: I should add that once you download the file from the web app, it opens fine in the word processor I use, Libreoffice (and I assume it would work with Microsoft Word, but I don't have it).  It would just be nice to able to preview the doc in the webapp on the off-chance that I'm not using my computer.

**Comment by odeke-em** [comment] 2015-04-22 03:12
Hello @jnazaroff thank you for reporting this and also welcome to drive!

The difference between the upload from the UI and that from drive is that the UI "actually tries to determine the mimeTyp"e of the uploaded document and that gets appropriately passed on to the file viewer, probably by Google Drive's internal file mimeType preprocessor.
This would mean that for a file uploaded by the UI, if it is say an *.odt file its mimetype will be registered as "application/vnd.oasis.opendocument.text", while drive having not preprocessed the file won't pass in the mimeType because it doesn't know what it is, and that mimeType gets read by Google's file viewer as well as Google Drive as "application/zip".

The tricky part so far on our side will be trying to guess the mimeType. If you'd like to actually step through this and see this discrepancy in action, let me know and I can show you how to reproduce and test the hypothesis.

I am going to dig as well as ask someone on the Drive team whether drive can get the file preprocessor to detect mimeTypes. We could also try to get a file mimeTyper package. There is also a dirty hacky that would involve letting the user pass in what their mimeType guess is but there are better ways :)
Please let me know if you have some suggestions or preferences.

Thank you.

**Comment by jnazaroff** [comment] 2015-04-22 03:22
@odeke-em: Thank you for your feedback!  If you're available, I'd love to help as best as I can.  I'm not a "noob," but I'm not fluent in any coding or anything, either.  I can work within terminal well enough (hence my using "drive".  :-) )

What would you like me to do?

**Comment by jnazaroff** [comment] 2015-04-22 03:26
@odeke-em: Also, I could see why finding the right mimetype could help.  Would the DevTools (F12 in Chrome) help at all?  For example, when I have Google's UI "open" a file, it will identify the mimeType (if possible) then move to the appropriate viewer if one is available.  Can any of that process be shown or identified via DevTools?

**Comment by odeke-em** [comment] 2015-04-22 03:29
Thank you. No worries, that shouldn't be a barrier at all, you reporting this is already a good step ;)
So amongst the alternatives, mimeType guessing by preprocessing the file before upload, similar to 
```shell
$ file <name_of_file>
```
which I presume reads a couple of bytes from a file then guesses the type based off those, or gets a magic number and makes a reference in its table of known magic numbers.
Or how would the user experience be for you if you could specify what type of file it is by extension?
e.g
```shell
$ drive push doc.docx --mime-guess docx
```
where the `--mime-guess` is a representative short form for the respective mime-type that will be hard set
ie
```go
{
    "csv":   "text/csv",
    "html?": "text/html",
    "te?xt": "text/plain",

    "gif":   "image/gif",
    "png":   "image/png",
    "svg":   "image/svg+xml",
    "jpe?g": "image/jpeg",

    "odt": "application/vnd.oasis.opendocument.text",
    "rtf": "application/rtf",
    "pdf": "application/pdf",

    "docx?": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "pptx?": "application/vnd.openxmlformats-officedocument.wordprocessingml.presentation",
    "xlsx?": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
}
```
These are currently experiments that we'll use to try to fix this.

**Comment by odeke-em** [comment] 2015-04-22 03:30
Hmm, I haven't used the Chrome dev or UI tools unfortunately but I'd think they should allow you to inspect the properties of a file.

**Comment by odeke-em** [comment] 2015-04-22 03:33
Let me whip up a branch to test out the user "guessed mime-type" and we can see how annoying or convenient that might be

**Comment by jnazaroff** [comment] 2015-04-22 03:38
Alright, sounds good.  

Incidentally, and I know I'm comparing apples to oranges here, but "grive" is what I used before; for some reason, the issue I posted above never happened with grive.  Is it possible they have a way to preprocess the mimeType?  I like "drive" for the many options it has over grive, so I plan on sticking with it; just seeing if there's a way to find out how they do it and get some ideas that way.  :)

**Comment by jnazaroff** [comment] 2015-04-22 03:40
I greatly appreciate you helping out, by the way!  :)  I'm sure most people using a terminal-based google drive tool are doing so mostly for backup reasons.  I like it for that reason but also because I can rest assured my files are accessible anytime, anywhere, and on any device, such as my phone.

**Comment by odeke-em** [comment] 2015-04-22 03:42
Good point, oh okay now that makes me suspect something or option that isn't being turned on by the API client in the worst case. I am not familiar with grive but if you could point me to it, and I can take a look at it. Btw has this been recent? Now weird thing is that for some files this doesn't happen.
Oh yes I too love having my files across devices, the joy for me is getting stuff from whatever computer then using them with my phone, people just wonder where I get all the memes hehe but it is from using drive from a computer and accessing it from a phone. Anyways mobile usage is way convenient.

**Comment by jnazaroff** [comment] 2015-04-22 03:47
https://github.com/Grive/grive/

From what I understand, yesterday Google is not using Documents List API.  Have you heard anything about this?  This is the reason grive is not working and why many people have switched to drive.  It is also the reason ES File Explorer's (for Android) Google Drive Integration feature is not working.  You can read about the problems with grive in Issues.

**Comment by odeke-em** [comment] 2015-04-22 03:52
Oh okay, yes I heard of the Documents List API being deprecated but that deals with Google Docs directly right? Also it was first deprecated in like 2012 but left functional for quite a bit, I guess it was about time. It sucks though that it had to be deprecated, but probably it was no longer maintained plus the Google Drive API has way more features.
Thanks for the link I'll check it out now.

**Comment by odeke-em** [comment] 2015-04-22 03:58
Grive doesn't look like it did any mimeType preprocessing locally, so am guessing that might have been within the Documents List API

**Comment by jnazaroff** [comment] 2015-04-22 04:02
Oh.  So the old API must have handled mimeType processing differently.  The new API probably has much more preprocessing done than the old one, right?  Maybe something's off on Google's end; maybe they were too focused on getting the files to work with their products or something and they missed some of the basics?  lol.

Would it help if I tried uploading any other file types, just to see how Google handles them?

**Comment by odeke-em** [comment] 2015-04-22 04:16
Could be plausible, never know.

Yes it would be, now if you are not familiar, drive supports stat-ing e.g
```shell
$ drive stat test-file
```
and you can use this to inspect the different set mimeTypes.

Thank you for undertaking this.

**Comment by jnazaroff** [comment] 2015-04-22 04:27
It's night time where I am,  so after some sleep,  I'll try and get on it.  Take care until then.  :)

**Comment by odeke-em** [comment] 2015-04-22 04:28
Thanks for your help and have a good night, it is night too here, catch you later :)

**Comment by odeke-em** [comment] 2015-04-22 05:06
Please take a look at PR https://github.com/odeke-em/drive/pull/155 and let's see if this can for now alleviate this issue.

**Comment by jnazaroff** [comment] 2015-04-22 09:11
Thanks, @odeke-em.  I'll have a go at it right now.  How can I do the "all is well" successful check like the others?  I'm also new to github, but I would like to learn how to contribute more.  :)

**Comment by odeke-em** [comment] 2015-04-22 09:18
Up early ? :)
All is well check? Do you mean continuous integration test, or testing out the PR?

Good stuff, definitely there is so much you'll be able to contribute, reporting and fixing this on its own is going to be a big win on its own.

Just in case you'd like to test out a patch you can go into the directory that drive, you probably already know this but just in case and for others: e.g to test out a patch on branch pr-1
```shell
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git fetch --all
$ git checkout pr-1
$ git pull origin pr-1 # In case you want to be absolutely sure that you have all the changes
$ go get github.com/odeke-em/drive/cmd/drive
```
I included in the README a section how to apply patches as well https://github.com/odeke-em/drive#applying-patches

**Comment by jnazaroff** [comment] 2015-04-22 09:21
@odeke-em I actually didn't know how to test branches.  Like i said, I'm new to all of it, but I'll read the README and try the commands above.  Thanks!  :)  

I'm up early to work on a paper due today.  Spent too much time yesterday working on this issue that I needed to get up early today and finish it.  :)  After all is said and done with my paper, I'll try the above.  Have a great day!

**Comment by odeke-em** [comment] 2015-04-22 09:24
No worries, you'll pick it up easily after a few tries.

Yap student life, I just had my last exam of the semester on Monday so I hear ye.
No worries, I'll let you focus. Am almost heading to bed here as well. Thanks and good luck on that paper!

**Comment by jnazaroff** [comment] 2015-04-22 09:27
Thanks!  And thank you for your help with this issue.  I'm hoping to contribute more once I graduate.  I'm an English major, but I'd like to learn some various program coding languages, etc., at some point in the future.

**Comment by odeke-em** [comment] 2015-04-22 09:33
Wow, that's pretty cool with the interest. Keep it up! Yeah folks that are language majors I've found actually dabble in computing quite a bit and even tend towards natural language processing, compilers etc as a natural progression. Nice, more reason to kick ass on that paper as you head towards graduation. We surely could use your skills here -- drive's manual, help utilities and documentation are really doing poorly grammar-wise yet clear communication gives a very big edge to projects.

**Comment by jnazaroff** [comment] 2015-04-22 09:43
If I have a little free time, I'd love to help edit some of your manuals and such.  :)

**Comment by odeke-em** [comment] 2015-04-22 09:46
And of course feel free to dive into the code as much, I mentioned the manual help because I hadn't encountered someone with this set of skills that was willing to help out. Good luck on that last paper, am off to bed.

**Comment by odeke-em** [comment] 2015-04-25 03:19
Addressed by PR https://github.com/odeke-em/drive/pull/155.

**Closed** 2015-04-25 03:20 UTC
