### ISSUE TITLE
"Last modification" not updated in google drive when using "-piped"

### ISSUE THREAD

**Issue by casperklein** [odeke-em/drive#392] opened 2015-09-24 22:02 UTC
I don't know if thats an issue in drive or in google drive generally.

When using this:

    date | drive push -piped -force date.txt

the content of date.txt gets updated every time I run the command. I verified that by opening the file in google drive. Unfortunately the "last modification" column is not updated. It keeps the date/time when the file was first pushed.

When I run "drive stat" directly after "drive push" I get this:

Filename                  date.txt
FileId                    xxxxxxxxxxxx
Bytes                     30
Size                      30.00B
DirType                   file
VersionNumber             18423
MimeType                  text/plain
Etag                      "xxxxxxxxxxxx"
ModTime                   2015-09-24 21:55:01 +0000 UTC
LastViewedByMe            2015-09-24 21:59:05 +0000 UTC
Shared                    false
Owners                    foo
LastModifyingUsername     foo
Md5Checksum               xxxxxxxxxxxxxxxxxx
Copyable                  true
Starred                   false
Viewed                    true
Trashed                   false
ViewersCanDownload        false

It seems only "LastViewedByMe" gets updated
ModTime is the time the file was first pushed.

**Comment by odeke-em** [comment] 2015-09-25 03:44
Hello again @casperklein.

Thank you for reporting this issue. Good catch. In deed it is a bug with drive. The cause of it is that when nonStatable content is pushed up, the source and destination are both the derived from the remote file and no modifications for the time are made. PR coming up in a second.

**Comment by odeke-em** [comment] 2015-09-25 03:48
Hello again @casperklein. Fixed by PR https://github.com/odeke-em/drive/pull/393. Please get the latest from master. Thank you for examining and reporting this issue.

**Closed by odeke-em** 2015-09-25 03:48 UTC
Labels: bug
