### ISSUE TITLE
Progress when pulling surpasses 100%

### ISSUE THREAD

**Issue by tomchor** [odeke-em/drive#691] opened 2016-07-12 00:43 UTC
Sorry for opening two issues in a row, this is a minor thing but I thought it might be worth communicating:

![screenshot from 2016-07-11 18 59 10](https://cloud.githubusercontent.com/assets/13205162/16751305/b12690c8-47ae-11e6-8ceb-11fb0d45eddc.png)

Frequently when pulling (I haven't seen this happen when pushing, but I didn't pay much attention) the progress bar goes way over 100%. In this particular case it stopped at 200% approximately:

` 6275620742 / 3132430367 [=======================================] 200.34% 1h9m58s`

Between the start and end of the pulling process I didn't change anything manually on the drive web interface by the way. I have no clue why this happens.

**Comment by odeke-em** [comment] 2016-07-12 01:22
Hello there @tomchor, it is no biggie at all :)
This issue is a duplicate of https://github.com/odeke-em/drive/issues/177 and https://github.com/odeke-em/drive/issues/669. Let's migrate the discussion to https://github.com/odeke-em/drive/issues/177.

**Closed** 2016-07-12 01:23 UTC

**Comment by odeke-em** [comment] 2016-11-07 06:29
Thanks for the patience, fixed by PR https://github.com/odeke-em/drive/pull/784.

Please get the latest from master by
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
