### ISSUE TITLE
Impossible to push

### ISSUE THREAD

**Issue by lhum** [odeke-em/drive#68] opened 2015-02-17 09:26 UTC
Hi !

After pulling a big folder successfully (at least it seems successful, no error), I copied 3 pdf in one of the subfolder, place myself in that subfolder and try
drive push
and got
credentials.json: no such file or directory
The result is the same if I try to push one new specific file.

I maybe missed something basic, could you please help me on that ?

**Comment by odeke-em** [comment] 2015-02-17 09:29
In order for you to push files, make sure that they are subpaths of the directory in which you initialized and authorized after `drive init`. Running drive outside that path will yield such warnings.

**Comment by odeke-em** [comment] 2015-02-17 09:30
If that isn't the issue, would you mind giving me the layout of your folders or a screenshot reproducing what happened? Also `drive version` please.

**Comment by lhum** [comment] 2015-02-17 09:43
Thanks for the fast reply. I'm sure to be in a subfolder where drive have access as it writes there when pulling news file. The complete error message gives the path
/home/usersFWM/elie/gdrive/research/All-topics-Bibliography/.gd/credentials.json: no such file or directory

drive version 0.0.9

simple test case
cd ~/gdrive
mkdir test
cd test
drive push
(succes)
then 
drive push
->open /home/usersFWM/elie/gdrive/test/.gd/credentials.json: no such file or directory

**Comment by odeke-em** [comment] 2015-02-17 09:55
That is an interesting error. I'll try reproducing it and examining what is going on, in the morning or later ie in about 16 hours when I get back home. If you'd like to avoid this show stopper, I could remedy for starters `cd <source_code_repo> && git fetch --all && git checkout tags/<desired_ release_tag>` where you can see the releases by `git tag -l`, inside the dir that you cloned this repo, then recompiling the source. The other releases have been used without this issue. Thank you for your patience.

**Comment by Walkman100** [comment] 2015-02-17 22:55
> I copied 3 pdf in one of the subfolder, place myself in that subfolder and try

I'm pretty sure you're not supposed to CD into the subfolder...

**Comment by odeke-em** [comment] 2015-02-18 01:42
@Walkman100 Actually you should be able to use drive in any path inside of the root directory.

@lhum Found the problem, the cause is that an index that gets created on every initialize, not in the root directory but in the path that is being initialize. This creates a ".gd/indices" path. Yet drive greedily finds the first ".gd" directory presented to it. You can test this out by:
```shell
$ mkdir -p new_path_in_drive && cd new_path_in_drive
$ ls -alR # This should show you only  "." and ".." as the listings
$ drive push . # Should be successful
$ ls -alR # You should now see a dir ".gd/indices"
$ mkdir test_dir && drive push test_dir # Should reproduce the error
```

This bug was introduced by https://github.com/odeke-em/drive/pull/64/files.

 Otherwise I'd recommend using code not on tag v0.0.9 as it contains the index creation for conflict tracking code. You can follow the remedy that I proposed in my second last comment.

Thank you for reporting it: I am on it right now and a fix should be coming up soon.

**Comment by odeke-em** [comment] 2015-02-18 03:17
@lhum and everyone else, if I may ask, would you mind taking a look at https://github.com/odeke-em/drive/pull/69? I have put up instructions on how to test the patch.

**Comment by lhum** [comment] 2015-02-18 08:28
Thanks for patching so fast, unfortunately I can not test it, as I don't have admin acces here and looks like the go compiler is not at the usual place, and not in the path. Thanks anyway

**Comment by odeke-em** [comment] 2015-02-18 16:19
@lhum that is unfortunate, please let me know if there is any way you'd like me to deliver the patch so that you can be able to test it.

**Comment by odeke-em** [comment] 2015-02-19 03:06
PR Merged into master. Please reopen if the problem persists.

**Closed by odeke-em** 2015-02-19 03:06 UTC
