### ISSUE TITLE
Panic when running drive pull

### ISSUE THREAD

**Issue by pefoley2** [odeke-em/drive#288] opened 2015-07-18 16:10 UTC
I got this when running drive pull.
Resolving...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x44cf27]

goroutine 4625 [running]:
github.com/odeke-em/drive/src.func·001(0x0, 0xc20860c3c0, 0xc2082e0c00, 0xc20842e2c0, 0xc20842e2a0, 0x13, 0xc208140b00, 0xd, 0x10)
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:317 +0x368
created by github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:329 +0xe48

goroutine 1 [semacquire, 7 minutes]:
sync.(*WaitGroup).Wait(0xc2082b1900)
        /usr/lib/go/src/sync/waitgroup.go:132 +0x169
github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv(0xc2080a9110, 0xecd3b9d00, 0x8ab090, 0x1, 0x8ab090, 0x1, 0xc20835a000, 0xc20835a140, 0x0, 0x0, ...)
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:333 +0xe8b
github.com/odeke-em/drive/src.(*Commands).doChangeListRecv(0xc2080a9110, 0x8ab090, 0x1, 0xc2080282d0, 0xb, 0xc20835a140, 0xc20835a000, 0x0, 0x0, 0x0, ...)
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:144 +0x27c
github.com/odeke-em/drive/src.(*Commands).byRemoteResolve(0xc2080a9110, 0x8ab090, 0x1, 0xc2080282d0, 0xb, 0xc20835a000, 0x0, 0x0, 0x0, 0x0, ...)
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:124 +0x152
github.com/odeke-em/drive/src.(*Commands).changeListResolve(0xc2080a9110, 0x8ab090, 0x1, 0xc2080282d0, 0xb, 0x424100, 0x0, 0x0, 0x0, 0x0, ...)
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:134 +0x175
github.com/odeke-em/drive/src.(*Commands).pullByPath(0xc2080a9110, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/peter/go/src/github.com/odeke-em/drive/src/pull.go:251 +0x190
github.com/odeke-em/drive/src.*Commands.(github.com/odeke-em/drive/src.pullByPath)·fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/peter/go/src/github.com/odeke-em/drive/src/pull.go:93 +0x75
github.com/odeke-em/drive/src.pullLikeResolve(0xc2080a9110, 0x894500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/peter/go/src/github.com/odeke-em/drive/src/pull.go:98 +0x2cb
github.com/odeke-em/drive/src.(*Commands).Pull(0xc2080a9110, 0xc208052100, 0x0, 0x0)
        /home/peter/go/src/github.com/odeke-em/drive/src/pull.go:52 +0x57
main.(*pullCmd).Run(0xc2080661b0, 0xc20800a010, 0x0, 0x0)
        /home/peter/go/src/github.com/odeke-em/drive/cmd/drive/main.go:535 +0x79a
github.com/odeke-em/command.Run()
        /home/peter/go/src/github.com/odeke-em/command/command.go:182 +0x99
github.com/odeke-em/command.ParseAndRun()
        /home/peter/go/src/github.com/odeke-em/command/command.go:189 +0x20
main.main()
        /home/peter/go/src/github.com/odeke-em/drive/cmd/drive/main.go:84 +0x1ab4

goroutine 5 [syscall, 7 minutes]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
github.com/odeke-em/cli-spinner.func·001()
        /home/peter/go/src/github.com/odeke-em/cli-spinner/spinner.go:100 +0x383
created by github.com/odeke-em/cli-spinner.(*Spinner).spin
        /home/peter/go/src/github.com/odeke-em/cli-spinner/spinner.go:103 +0x13f

goroutine 33 [syscall, 7 minutes, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 36 [IO wait]:
net.(*pollDesc).Wait(0xc2080a0220, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080a0220, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080a01c0, 0xc208548000, 0x8000, 0x8000, 0x0, 0x7f0fef73fcd0, 0xc20829fac0)
        /usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20804c048, 0xc208548000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc2082e64b0, 0x7f0fef741bb0, 0xc20804c048, 0x5, 0x0, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208310000, 0x17, 0x0, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208310000, 0xc20831a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f0fef74b588, 0xc208310000, 0xc20830a058, 0xc20831a000, 0x1000, 0x1000, 0x7d1bc0, 0x0, 0x0)
        /usr/lib/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208325ee0, 0xc20831a000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2083049c0)
        /usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2083049c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20830a000)
        /usr/lib/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:660 +0xc9f

goroutine 37 [select]:
net/http.(*persistConn).writeLoop(0xc20830a000)
        /usr/lib/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:661 +0xcbc

goroutine 20 [semacquire]:
sync.(*WaitGroup).Wait(0xc208481e20)
        /usr/lib/go/src/sync/waitgroup.go:132 +0x169
github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv(0xc2080a9110, 0x0, 0x8ab090, 0x1, 0xc2082b6000, 0xe, 0xc208367900, 0xc208312a00, 0x0, 0x0, ...)
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:333 +0xe8b
github.com/odeke-em/drive/src.func·001(0x0, 0xc2082b1900, 0xc20836b300, 0xc2082d46c0, 0x8ab090, 0x1, 0xc2082b8000, 0x25, 0x40)
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:315 +0x219
created by github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:329 +0xe48

goroutine 4551 [runnable]:
sync.(*WaitGroup).Wait(0xc20860c3c0)
        /usr/lib/go/src/sync/waitgroup.go:132 +0x169
github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv(0xc2080a9110, 0x0, 0xc2082b6000, 0xe, 0xc20842e2a0, 0x13, 0xc208157040, 0xc2084d5180, 0x0, 0x0, ...)
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:333 +0xe8b
github.com/odeke-em/drive/src.func·001(0x0, 0xc208481e20, 0xc2084c4e00, 0xc20860c980, 0xc2082b6000, 0xe, 0xc208122680, 0xa, 0x10)
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:315 +0x219
created by github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv
        /home/peter/go/src/github.com/odeke-em/drive/src/changes.go:329 +0xe48

**Comment by odeke-em** [comment] 2015-07-18 17:59
Hello @pefoley2 thank you for reporting this issue and welcome to drive!

For starters would you mind giving me your `drive version`.
If you built this from source and it gives you variable version information, please make sure to have built it like this
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by pefoley2** [comment] 2015-07-18 18:43
drive version: 0.2.6
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>

I used go get -u github.com/odeke-em/drive/cmd/drive to install.
I haven't been able to reproduce the crash, though.

**Comment by odeke-em** [comment] 2015-07-24 03:40
@pefoley2 ping! And you were sure that you had the latest code when you first tried it?

**Comment by pefoley2** [comment] 2015-07-24 23:59
Yeah, but I haven't run into the crash since.

**Comment by odeke-em** [comment] 2015-08-01 02:02
Can't reproduce this issue unfortunately.

**Comment by canpolat** [comment] 2015-08-01 10:52
I just got this issue. I use the AUR package for Manjaro. Manjaro notified me of an update and I accepted it. When I ran drive right after that update I got the output shown below. When I re-ran the same command (`drive push`), everythig went OK. I'm not sure that this is related to the update, but that's how it happened.

	panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x0 pc=0x44cded]

	goroutine 91 [running]:
	github.com/odeke-em/drive/src.(*Commands).changeSlice(0xc2080b1470, 0xc20919faa0, 0x26, 0xc2084f9860, 0xe01, 0xc2082cb320, 0xc2082b8a50, 0x22, 0xc208b756c0, 0x20, ...)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:364 +0x3d7
	created by github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:326 +0xd94

	goroutine 1 [semacquire]:
	sync.(*WaitGroup).Wait(0xc2082ca040)
		/usr/lib/go/src/sync/waitgroup.go:132 +0x169
	github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv(0xc2080b1470, 0xc2082d2280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:330 +0xdd5
	github.com/odeke-em/drive/src.(*Commands).doChangeListRecv(0xc2080b1470, 0xc2080b8830, 0xc, 0xc20803cd80, 0x21, 0xc2082f6140, 0xc2082f6000, 0x1, 0x0, 0x0, ...)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:153 +0x323
	github.com/odeke-em/drive/src.(*Commands).byRemoteResolve(0xc2080b1470, 0xc2080b8830, 0xc, 0xc20803cd80, 0x21, 0xc2082f6000, 0x1, 0x0, 0x0, 0x0, ...)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:125 +0x19e
	github.com/odeke-em/drive/src.(*Commands).changeListResolve(0xc2080b1470, 0xc2080b8830, 0xc, 0xc20803cd80, 0x21, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:135 +0x175
	github.com/odeke-em/drive/src.(*Commands).Push(0xc2080b1470, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/push.go:61 +0x585
	main.(*pushCmd).Run(0xc208060080, 0xc20800a010, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/cmd/drive/main.go:595 +0x1cf
	github.com/odeke-em/command.Run()
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/command/command.go:197 +0x99
	github.com/odeke-em/command.ParseAndRun()
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/command/command.go:204 +0x20
	main.main()
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/cmd/drive/main.go:84 +0x1ab4

	goroutine 5 [syscall]:
	os/signal.loop()
		/usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
	created by os/signal.init·1
		/usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

	goroutine 6 [chan receive]:
	github.com/odeke-em/cli-spinner.func·001()
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/cli-spinner/spinner.go:100 +0x383
	created by github.com/odeke-em/cli-spinner.(*Spinner).spin
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/cli-spinner/spinner.go:103 +0x13f

	goroutine 17 [chan receive]:
	github.com/odeke-em/drive/src.func·028()
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/push.go:50 +0x64
	created by github.com/odeke-em/drive/src.(*Commands).Push
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/push.go:54 +0x436

	goroutine 20 [chan receive]:
	github.com/odeke-em/drive/src.merge(0xc208b32900, 0xc208b328a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:401 +0x23d
	github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv(0xc2080b1470, 0xc2093bd680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:286 +0x731
	github.com/odeke-em/drive/src.(*Commands).changeSlice(0xc2080b1470, 0xc20919faa0, 0x0, 0xc2084f9860, 0xe01, 0xc2082cb320, 0xc2082b8a50, 0x22, 0xc208b6e000, 0x64, ...)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:362 +0x288
	created by github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:326 +0xd94

	goroutine 8 [IO wait]:
	net.(*pollDesc).Wait(0xc2080a8060, 0x72, 0x0, 0x0)
		/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc2080a8060, 0x0, 0x0)
		/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).Read(0xc2080a8000, 0xc208292000, 0x800, 0x800, 0x0, 0x7f8f5035acd0, 0xc208102030)
		/usr/lib/go/src/net/fd_unix.go:242 +0x40f
	net.(*conn).Read(0xc208108008, 0xc208292000, 0x800, 0x800, 0x0, 0x0, 0x0)
		/usr/lib/go/src/net/net.go:121 +0xdc
	crypto/tls.(*block).readFromUntil(0xc2081061b0, 0x7f8f5035cb20, 0xc208108008, 0x5, 0x0, 0x0)
		/usr/lib/go/src/crypto/tls/conn.go:454 +0xe6
	crypto/tls.(*Conn).readRecord(0xc208118000, 0x17, 0x0, 0x0)
		/usr/lib/go/src/crypto/tls/conn.go:539 +0x2da
	crypto/tls.(*Conn).Read(0xc208118000, 0xc208124000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/lib/go/src/crypto/tls/conn.go:904 +0x166
	net/http.noteEOFReader.Read(0x7f8f503654b0, 0xc208118000, 0xc208104058, 0xc208124000, 0x1000, 0x1000, 0x7d3f20, 0x0, 0x0)
		/usr/lib/go/src/net/http/transport.go:1270 +0x6e
	net/http.(*noteEOFReader).Read(0xc208199bc0, 0xc208124000, 0x1000, 0x1000, 0xc208014400, 0x0, 0x0)
		<autogenerated>:125 +0xd4
	bufio.(*Reader).fill(0xc2080ea240)
		/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
	bufio.(*Reader).Peek(0xc2080ea240, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/lib/go/src/bufio/bufio.go:132 +0xf0
	net/http.(*persistConn).readLoop(0xc208104000)
		/usr/lib/go/src/net/http/transport.go:842 +0xa4
	created by net/http.(*Transport).dialConn
		/usr/lib/go/src/net/http/transport.go:660 +0xc9f

	goroutine 49 [syscall, locked to thread]:
	runtime.goexit()
		/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

	goroutine 9 [select]:
	net/http.(*persistConn).writeLoop(0xc208104000)
		/usr/lib/go/src/net/http/transport.go:945 +0x41d
	created by net/http.(*Transport).dialConn
		/usr/lib/go/src/net/http/transport.go:661 +0xcbc

	goroutine 38 [IO wait]:
	net.(*pollDesc).Wait(0xc2080ae290, 0x72, 0x0, 0x0)
		/usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc2080ae290, 0x0, 0x0)
		/usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).Read(0xc2080ae230, 0xc208b9a000, 0x8000, 0x8000, 0x0, 0x7f8f5035acd0, 0xc208c75278)
		/usr/lib/go/src/net/fd_unix.go:242 +0x40f
	net.(*conn).Read(0xc2080ee070, 0xc208b9a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
		/usr/lib/go/src/net/net.go:121 +0xdc
	crypto/tls.(*block).readFromUntil(0xc208126510, 0x7f8f5035cb20, 0xc2080ee070, 0x5, 0x0, 0x0)
		/usr/lib/go/src/crypto/tls/conn.go:454 +0xe6
	crypto/tls.(*Conn).readRecord(0xc20800cdc0, 0x17, 0x0, 0x0)
		/usr/lib/go/src/crypto/tls/conn.go:539 +0x2da
	crypto/tls.(*Conn).Read(0xc20800cdc0, 0xc2082b6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/lib/go/src/crypto/tls/conn.go:904 +0x166
	net/http.noteEOFReader.Read(0x7f8f503654b0, 0xc20800cdc0, 0xc2082ac058, 0xc2082b6000, 0x1000, 0x1000, 0x7d3f20, 0x0, 0x0)
		/usr/lib/go/src/net/http/transport.go:1270 +0x6e
	net/http.(*noteEOFReader).Read(0xc2082797a0, 0xc2082b6000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
		<autogenerated>:125 +0xd4
	bufio.(*Reader).fill(0xc208062fc0)
		/usr/lib/go/src/bufio/bufio.go:97 +0x1ce
	bufio.(*Reader).Peek(0xc208062fc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/lib/go/src/bufio/bufio.go:132 +0xf0
	net/http.(*persistConn).readLoop(0xc2082ac000)
		/usr/lib/go/src/net/http/transport.go:842 +0xa4
	created by net/http.(*Transport).dialConn
		/usr/lib/go/src/net/http/transport.go:660 +0xc9f

	goroutine 39 [select]:
	net/http.(*persistConn).writeLoop(0xc2082ac000)
		/usr/lib/go/src/net/http/transport.go:945 +0x41d
	created by net/http.(*Transport).dialConn
		/usr/lib/go/src/net/http/transport.go:661 +0xcbc

	goroutine 19 [semacquire]:
	sync.(*WaitGroup).Wait(0xc208279920)
		/usr/lib/go/src/sync/waitgroup.go:132 +0x169
	github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv(0xc2080b1470, 0xc2080e3c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:330 +0xdd5
	github.com/odeke-em/drive/src.(*Commands).changeSlice(0xc2080b1470, 0xc2082b8030, 0x0, 0xc2082ca040, 0x1, 0xc2082ce620, 0xc2080b8830, 0xc, 0xc2082d2c00, 0x6, ...)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:362 +0x288
	created by github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:326 +0xd94

	goroutine 40 [semacquire]:
	sync.(*WaitGroup).Wait(0xc2084f9860)
		/usr/lib/go/src/sync/waitgroup.go:132 +0x169
	github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv(0xc2080b1470, 0xc2082a4e40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:330 +0xdd5
	github.com/odeke-em/drive/src.(*Commands).changeSlice(0xc2080b1470, 0xc208127800, 0x0, 0xc208279920, 0x1, 0xc208320020, 0xc208320000, 0x19, 0xc20821ecc0, 0x5, ...)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:362 +0x288
	created by github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:326 +0xd94

	goroutine 14 [select]:
	net/http.(*persistConn).roundTrip(0xc2082ac000, 0xc208c75d10, 0x0, 0x0, 0x0)
		/usr/lib/go/src/net/http/transport.go:1082 +0x7ad
	net/http.(*Transport).RoundTrip(0xc208070090, 0xc20810b790, 0xc20810b790, 0x0, 0x0)
		/usr/lib/go/src/net/http/transport.go:235 +0x558
	golang.org/x/oauth2.(*Transport).RoundTrip(0xc2080b12f0, 0xc20810b5f0, 0xc208790b80, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/golang.org/x/oauth2/transport.go:48 +0x2aa
	net/http.send(0xc20810b5f0, 0x7f8f5035b988, 0xc2080b12f0, 0x76, 0x0, 0x0)
		/usr/lib/go/src/net/http/client.go:219 +0x4fc
	net/http.(*Client).send(0xc2080b1320, 0xc20810b5f0, 0x76, 0x0, 0x0)
		/usr/lib/go/src/net/http/client.go:142 +0x15b
	net/http.(*Client).doFollowingRedirects(0xc2080b1320, 0xc20810b5f0, 0x99d9a0, 0x0, 0x0, 0x0)
		/usr/lib/go/src/net/http/client.go:367 +0xb25
	net/http.(*Client).Do(0xc2080b1320, 0xc20810b5f0, 0xa, 0x0, 0x0)
		/usr/lib/go/src/net/http/client.go:174 +0xa4
	github.com/google/google-api-go-client/drive/v2.(*FilesListCall).Do(0xc208c759b0, 0x0, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/google/google-api-go-client/drive/v2/drive-gen.go:4193 +0x1324
	github.com/odeke-em/drive/src.func·034()
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/remote.go:208 +0x166
	created by github.com/odeke-em/drive/src.reqDoPage
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/remote.go:239 +0x1f6

	goroutine 85 [runnable]:
	strings.Join(0xc208b2ff60, 0x2, 0x2, 0x8ad800, 0x1, 0x0, 0x0)
		/usr/lib/go/src/strings/strings.go:394 +0xfd
	github.com/odeke-em/drive/src.sepJoin(0x8ad800, 0x1, 0xc208b2ff60, 0x2, 0x2, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/misc.go:150 +0x62
	github.com/odeke-em/drive/src.(*Commands).changeSlice(0xc2080b1470, 0xc20919faa0, 0x20, 0xc2084f9860, 0xe01, 0xc2082cb320, 0xc2082b8a50, 0x22, 0xc208b74400, 0x64, ...)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:351 +0x86c
	created by github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:326 +0xd94

	goroutine 87 [runnable]:
	github.com/odeke-em/drive/src.(*Commands).changeSlice(0xc2080b1470, 0xc20919faa0, 0x22, 0xc2084f9860, 0xe01, 0xc2082cb320, 0xc2082b8a50, 0x22, 0xc208b74a40, 0x64, ...)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:359 +0x19a
	created by github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:326 +0xd94

	goroutine 90 [runnable]:
	github.com/odeke-em/drive/src.sepJoin(0x8ad800, 0x1, 0xc208b22760, 0x2, 0x2, 0x0, 0x0)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/misc.go:149
	github.com/odeke-em/drive/src.(*Commands).changeSlice(0xc2080b1470, 0xc20919faa0, 0x25, 0xc2084f9860, 0xe01, 0xc2082cb320, 0xc2082b8a50, 0x22, 0xc208b753a0, 0x64, ...)
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:351 +0x86c
	created by github.com/odeke-em/drive/src.(*Commands).resolveChangeListRecv
		/tmp/yaourt-tmp-user/aur-drive/src/drive-0.2.7/src/github.com/odeke-em/drive/src/changes.go:326 +0xd94

**Comment by odeke-em** [comment] 2015-08-01 12:05
Thanks @canpolat for raising this and my apologies for this issue. I'll take a look at it when I wake up.

**Comment by odeke-em** [comment] 2015-08-11 03:49
@canpolat & @pefoley2  have y'all encountered this again lately?

**Comment by pefoley2** [comment] 2015-08-11 03:57
Nope, haven't seen it since.

**Comment by canpolat** [comment] 2015-08-11 06:35
No. That was the only time I saw that error.

**Comment by odeke-em** [comment] 2015-08-11 06:37
Aye aye, thanks for the feedback. Maybe let's close this issue then, and probably re-open it if anyone re-encounters it.

**Closed** 2015-08-13 03:01 UTC
