### ISSUE TITLE
pull doesn't?

### ISSUE THREAD

**Issue by MWP** [odeke-em/drive#241] opened 2015-06-21 05:45 UTC
Greetings all,

Im using this for the first time on a Debian box.
Ive built drive from the GIT source (i assume its master?) using the provided instructions.

I ran "drive init", gave it the needed key. All good.
I run "drive list", i get a list of root files, root sub-folders and shared folders. All good.

According to the instructions, i should just be able to run "drive pull", and everything will be downloaded.
It downloads nothing.

The only way i can seem to download from gdrive, is by specifying all the files / sub-directories on the command line.
Ie: drive pull -force -r -no-prompt 'SharedDocs'
Then it will pull that directory just fine.

Why isnt "drive pull" working?
How can i diagnose the problem?

Thanks!

**Comment by odeke-em** [comment] 2015-06-21 05:49
Hello @MWP, thank you for installing and welcome to drive!

For starters, what does `drive version` produce? If not please run
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
```

To get you started, please make sure you `cd` into at least the root.
Secondly, can you make sure to not have conflicts and clashing files. Also what does
`drive pull` give you. `drive pull --force -r --no-prompt` does not give you the appropriate warnings or messages.

**Comment by MWP** [comment] 2015-06-21 08:12
I gather its not meant to report this...
drive version: 0.2.4
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>

It was built using "go get -u github.com/odeke-em/drive/cmd/drive" about 4hrs ago.
Go is version 1.4.2 (downloaded & installed the amd64 binaries today).

Running "drive pull" in the same dir where i ran the "drive init" gives:
Resolving...
X /CCCSA/2015-02 Minutes.odt "(removed the key, not sure if this should be kept secret?)"
Everything is up-to-date.

... and that is it.
It doesnt pull down any of the contents of the google drive root (5 dirs, 4 files).

Thanks.

**Comment by MWP** [comment] 2015-06-21 08:15
Markdown removed the gt/lt brackets...

#drive version
drive version: 0.2.4
Commit Hash: (CURRENT_COMMIT)
Go Version: (GO_VERSION)
OS: (OS_INFO)

**Comment by odeke-em** [comment] 2015-06-21 08:15
Unfortunately that doesn't give me the commit information. Please run as previously requested:
`$ go get github.com/odeke-em/drive/drive-gen && drive-gen`

So as you can see, it has conflicts and clashes and if you look at the warnings it provides, it asks you to resolve your conflicts and clashes otherwise it won't pull anything down.

**Comment by MWP** [comment] 2015-06-21 10:56
Ah, my mistake.
drive version: 0.2.4
Commit Hash: '64ca08fcce5c0c725a64ae1373006be110acdf9a'
Go Version: go1.4.2
OS: linux/amd64

Im not seeing the warnings you mention or anything about conflicts. I just get the red X with the file name, then "Everything is up-to-date" and that's it.
If there was some descriptive message, i probably could have solved this myself.

I've just looked through the README, and it mentions the ignore-conflict option, but nothing else?

Thanks again.

**Comment by odeke-em** [comment] 2015-06-21 10:58
Gotcha. My apologies for the non-descriptive error message then. Please take a look at issue https://github.com/odeke-em/drive/issues/222. I think this issue is a duplicate of it in that case.

**Comment by MWP** [comment] 2015-06-21 15:33
No apologies needed.
Where to from here?

To be honest, the extreme quietness during the build, install and use of drive has been rather odd.
Very un-console admin utility like behaviour.

**Comment by odeke-em** [comment] 2015-06-21 20:24
Addressed by PR https://github.com/odeke-em/drive/pull/244. Thank you reporting this.

**Closed by odeke-em** 2015-06-21 20:24 UTC
Labels: duplicate
