### ISSUE TITLE
Upon encountering a clash, `push` does not give details of the clashing path

### ISSUE THREAD

**Issue by js-ojus** [odeke-em/drive#261] opened 2015-06-30 03:33 UTC
When a path/name clash is detected, `push` aborts, but without providing any details of the path/name that resulted in a clash.

Currently, it leaves the user with no clue of where - in the directory tree - to look for the clash.

**Comment by js-ojus** [comment] 2015-06-30 03:39
I have opened #262 for the intended behaviour of `pull`.  I think that `push` should mirror that behaviour, too.

**Comment by odeke-em** [comment] 2015-06-30 05:48
What version of drive are you on? This is because I cannot seem to reproduce this.
![screen shot 2015-06-29 at 11 48 27 pm](https://cloud.githubusercontent.com/assets/4898263/8424564/607bbbb8-1eb9-11e5-93c8-ad5cb4e2f252.png)

**Comment by js-ojus** [comment] 2015-06-30 05:52
Here is the version.

```
js@karta:~ > drive version
drive version: 0.2.5
Commit Hash: '49c20a65dd78f0939435c01b80f944bb31b01056'
Go Version: go1.4.2
OS: linux/amd64
```

**Comment by odeke-em** [comment] 2015-06-30 05:53
And the screenshot of the clashes?

**Comment by js-ojus** [comment] 2015-06-30 05:58
Unfortunately, @odeke-em, I had to reboot in between.  I forgot making a copy of the output before rebooting :-(.

However, the test case is that I had a few files that were uploaded through GDrive's web interface (a while ago, before I started trying `drive`).  During those days, a few files accidentally got uploaded twice.  GDrive, evidently, doesn't complain.

This morning, I did a `push`, and it aborted giving no information of the clash(es) itself (themselves).

The one output at a time relates to `pull`, as described in #262.

I shall try to reproduce the test case, and let you know the outcome.

**Comment by odeke-em** [comment] 2015-06-30 06:00
Oh okay, no worries. In that screenshot above I provided a way to create clashes and test it out.

**Comment by js-ojus** [comment] 2015-06-30 06:08
I have been able to reproduce it, @odeke-em.  Here is a trivial test.

```
js@karta:~/gdrive > ll
total 12
drwxr-xr-x 5 js js 4096 Jun 19 21:08 Documents/
drwxr-xr-x 2 js js 4096 Jun 15 23:56 Music/
drwxr-xr-x 8 js js 4096 Jun 16 22:48 Pictures/
js@karta:~/gdrive > mkdir test-clashes-1
js@karta:~/gdrive > cd test-clashes-1/
js@karta:~/gdrive/test-clashes-1 > cp ~/tmp/lang/go/text/test.go .
js@karta:~/gdrive/test-clashes-1 > cd ..
js@karta:~/gdrive > drive push test-clashes-1
Resolving...
+ /test-clashes-1
+ /test-clashes-1/test.go
Addition count 2 src: 3.79KB
Proceed with the changes? [Y/n]:y
3881 / 3881 [======================================================] 100.00 % 4s
js@karta:~/gdrive > ll
total 16
drwxr-xr-x 5 js js 4096 Jun 19 21:08 Documents/
drwxr-xr-x 2 js js 4096 Jun 15 23:56 Music/
drwxr-xr-x 8 js js 4096 Jun 16 22:48 Pictures/
drwxr-xr-x 2 js js 4096 Jun 30 11:32 test-clashes-1/
js@karta:~/gdrive > cd test-clashes-1/
js@karta:~/gdrive/test-clashes-1 > ll
total 12
-rw-r--r-- 1 js js 3881 Jun 30 11:32 test.go
```

At this point, I used GDrive's web interface to uploaded the **same** file `test.go` to the same directory `test-clashes-1`.

```
js@karta:~/gdrive/test-clashes-1 > drive list -l
-- owner       3.79KB           0B8MR1cu9CxQ5WFBRNXFUeWl3dnc            2015-06-30 06:03:16 +0000 UTC   /test-clashes-1/test.go                           
-- owner       3.79KB           0B8MR1cu9CxQ5STZrWTJQR1NxOG8            2015-06-30 06:02:32 +0000 UTC   /test-clashes-1/test.go                           
js@karta:~/gdrive/test-clashes-1 > touch test.go 
js@karta:~/gdrive/test-clashes-1 > drive push
Resolving...
clashes detected. use `ignore-name-clashes` to override this behavior
```

As you can see, `push` gives no information as to what has caused the clash.

**Comment by odeke-em** [comment] 2015-06-30 06:14
Aha, I see I was able to reproduce it with the local touch and push instead of just the plain remote copy. This bug crept in last Thursday, I think I remember how this came in. Thank you for detailing how to reproduce it.

**Comment by odeke-em** [comment] 2015-07-01 14:35
Thank you @js-ojus for reporting this issue and for the detailed cases for reproducing it. Addressed by https://github.com/odeke-em/drive/pull/266. Please re-open if the problem persists.

**Closed by odeke-em** 2015-07-01 14:35 UTC
Labels: bug
