### ISSUE TITLE
req.Cancel undefined (type *http.Request has no field or method Cance

### ISSUE THREAD

**Issue by lth2h** [odeke-em/drive#655] opened 2016-05-25 22:56 UTC
On a fresh install of Ubuntu.

root@mybox: ~/google_drive # go get -u github.com/odeke-em/drive/drive-google

\# golang.org/x/sys/unix
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:38: clen redeclared in this block
	previous declaration at ../gopath/src/golang.org/x/sys/unix/syscall_linux.go:808
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:51: ParseDirent redeclared in this block
	previous declaration at ../gopath/src/golang.org/x/sys/unix/syscall_linux.go:821
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:77: Pipe redeclared in this block
	previous declaration at ../gopath/src/golang.org/x/sys/unix/syscall_linux_amd64.go:110
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:89: (*SockaddrInet4).sockaddr redeclared in this block
	previous declaration at ../gopath/src/golang.org/x/sys/unix/syscall_linux.go:302
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:103: (*SockaddrInet6).sockaddr redeclared in this block
	previous declaration at ../gopath/src/golang.org/x/sys/unix/syscall_linux.go:316
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:118: (*SockaddrUnix).sockaddr redeclared in this block
	previous declaration at ../gopath/src/golang.org/x/sys/unix/syscall_linux.go:331
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:144: Getsockname redeclared in this block
	previous declaration at ../gopath/src/golang.org/x/sys/unix/syscall_linux.go:516
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:153: ImplementsGetwd redeclared in this block
	previous declaration at ../gopath/src/golang.org/x/sys/unix/syscall_linux.go:175
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:157: Getwd redeclared in this block
	previous declaration at ../gopath/src/golang.org/x/sys/unix/syscall_linux.go:179
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:178: Getgroups redeclared in this block
	previous declaration at ../gopath/src/golang.org/x/sys/unix/syscall_linux.go:192
../gopath/src/golang.org/x/sys/unix/syscall_solaris.go:178: too many errors
\# golang.org/x/net/context/ctxhttp
../gopath/src/golang.org/x/net/context/ctxhttp/ctxhttp.go:35: req.Cancel undefined (type *http.Request has no field or method Cancel)

How do I make it work?

**Comment by shaggytwodope** [comment] 2016-05-25 23:01
It may be alot simpler to use the ppa, but if that isn't to you're liking can you post the output of `go version` . This is most likely a duplicate of #627.

**Comment by odeke-em** [comment] 2016-05-27 00:04
Hello there @lth2h thank you for reporting this issue and welcome to drive.

Yap, @shaggytwodope nailed it, in deed it is a duplicate of that issue. Please install at least Go1.5 and it should be good to use. The Go1.5 requirement is documented in the README as well.

**Comment by odeke-em** [comment] 2016-06-11 07:04
Closing since we know you'll need to upgrade to Go1.5. Please feel free to file any further related issues here or by opening a new one.

**Closed by odeke-em** 2016-06-11 07:04 UTC
