### ISSUE TITLE
On Ubuntu 100% is always exceeded 

### ISSUE THREAD

**Issue by malteseunderdog** [odeke-em/drive#505] opened 2015-11-29 21:08 UTC
This always happens ... I do not add/remove anything to the directory. 

```Modification count 5 src: 2.76MB dest: 2.76MB
Proceed with the changes? [Y/n]:
76425767 / 52676894 [========================================================================================================================================================================] 145.08 % 3m56```

**Comment by odeke-em** [comment] 2015-11-29 21:09
Hello @malteseunderdog! Thanks for reporting this and welcome to drive.

Could you give more context to this issue? What operations does this happen on? What version are you using? Any other information to help reproduce this?

**Comment by malteseunderdog** [comment] 2015-11-29 21:31
Apologies.  This happens on Ubuntu 14.04 when I do "drive push mydir"

jp@jp-Galago-UltraPro:~$ drive version
drive version: 0.3.2
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 

What other info do you need?  I love this little utility.

**Comment by odeke-em** [comment] 2015-11-29 21:54
Thanks for that information @malteseunderdog. So this issue was already reported in https://github.com/odeke-em/drive/issues/177.

**Comment by odeke-em** [comment] 2015-12-01 03:21
@malteseunderdog closing this as it is a duplicate of https://github.com/odeke-em/drive/issues/177

**Closed by odeke-em** 2015-12-01 03:21 UTC
