### ISSUE TITLE
404 File not found

### ISSUE THREAD

**Issue by mhollands** [odeke-em/drive#780] opened 2016-10-30 18:55 UTC
When I do a pull, I get this error:

err: download: failed for url "<my url name>". StatusCode: 404

This is for every file in my google drive. This was working a month ago or so. Running Debian Jessie. Any idea why this is happening? I can download the files from the web client just fine

**Comment by odeke-em** [comment] 2016-10-30 21:46
Hello there @mhollands, thanks for reporting this issue and welcome to drive.

Google shutdown /host/fileId hosting at the end of August and we patched that to change the origin.  Please get the latest by
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
``` 

This issue is a duplicate of closed ones https://github.com/odeke-em/drive/issues/776 https://github.com/odeke-em/drive/issues/766 and https://github.com/odeke-em/drive/issues/764.
I believe you are using an old version of drive.

**Comment by mhollands** [comment] 2016-10-30 23:59
Awesome! Thanks, I have now updated.

I thought that I had updated it, but turns out the update failed because I also hadn't updated my Go! Thanks for supporting this awesome tool - really is exactly what I need, instead of the annoying auto-syncing that google drive normally does.

**Comment by odeke-em** [comment] 2016-10-31 00:58
Good to know it worked for you!

Thank you for the kind words! Yap, lots of people share your woes about auto sync, myself included :)

I'll close this issue then since the update solved it for you.

**Closed by odeke-em** 2016-10-31 00:58 UTC

**Comment by shaggytwodope** [comment] 2016-10-31 01:35
@mhollands worth mentioning that we have packages made for some distros already. Be sure to look at https://github.com/odeke-em/drive/blob/master/platform_packages.md so that you may be able to auto update drive.
