### ISSUE TITLE
googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded

### ISSUE THREAD

**Issue by recursionbane** [odeke-em/drive#598] opened 2016-03-08 20:42 UTC
I consistently see this error when `push`ing from large directories (5GB with thousands of files):

`googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded`

Assuming unlimited bandwidth and a large number of files to upload, drive _could_ implement [exponential back-off](https://developers.google.com/analytics/devguides/reporting/core/v3/coreErrors#500) as suggested by the [Google Developer's guide](https://developers.google.com/analytics/devguides/reporting/core/v3/coreErrors#standard_errors).

> Code: 403	
> Reason: userRateLimitExceeded	
> Description: Indicates that the user rate limit has been exceeded. The maximum rate limit is 10 qps per IP address. The default value set in Google Developers Console is 1 qps per IP address. You can increase this limit in the Google Developers Console to a maximum of 10 qps.	
> Recommended Action: Retry using exponential back-off. You need to slow down the rate at which you are sending the requests.

Related: #240

**Comment by odeke-em** [comment] 2016-03-11 09:54
Hello there @recursionbane, thanks for reporting and welcome to drive!

So this issue is a duplicate of https://github.com/odeke-em/drive/issues/480.
Same train of thought, exponential back-off was already added in PR https://github.com/odeke-em/drive/pull/321 and PR https://github.com/odeke-em/drive/pull/318.

You can actually see the exponential backoff retries in action by setting flag `--verbose` e.g
```shell
$ drive push --verbose items a1 bxf
```
And if the max number of tries is exhausted, it fails and returns the error.

The problem manifests from two possible issues:
a) a bug with Google's backend where rate limits are improperly accounted.
b) the default credentials used in this project are used by lots of people around the world and the bug mentioned in a) gets aggravated by exhaustion.
You can try to alleviate by setting `GOOGLE_API_CLIENT_ID` and `GOOGLE_API_CLIENT_SECRET` in your env before running drive. Please see https://github.com/odeke-em/drive#configuration.

**Comment by odeke-em** [comment] 2016-03-25 08:46
Duplicate of #480

**Closed by odeke-em** 2016-03-25 08:46 UTC
Labels: duplicate
