### ISSUE TITLE
Nil pointer dereference in remote.go

### ISSUE THREAD

**Issue by sselph** [odeke-em/drive#217] opened 2015-05-30 00:04 UTC
```
resp, err := r.transport.Client().Get(url)
if err != nil || resp.StatusCode < 200 || resp.StatusCode > 299 {
  return resp.Body, err
}
```

Looks like remote.go:328 has an nil pointer dereference. Looks like if err is not nil, resp could be nil.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ac963]
goroutine 2177 [running]:
github.com/odeke-em/drive/src.(*Remote).Download(0xc20801e920, 0xc208b4d3a0, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sselph/go/src/github.com/odeke-em/drive/src/remote.go:328 +0x1e3
github.com/odeke-em/drive/src.(*Commands).singleDownload(0xc20800bcb0, 0xc208e57380, 0x0, 0x0)
	/home/sselph/go/src/github.com/odeke-em/drive/src/pull.go:549 +0x3cc
github.com/odeke-em/drive/src.(*Commands).download(0xc20800bcb0, 0xc20931da40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sselph/go/src/github.com/odeke-em/drive/src/pull.go:474 +0x1bd
github.com/odeke-em/drive/src.(*Commands).localAdd(0xc20800bcb0, 0xc208e6d400, 0xc20931da40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sselph/go/src/github.com/odeke-em/drive/src/pull.go:352 +0x237
created by github.com/odeke-em/drive/src.(*Commands).playPullChanges
	/home/sselph/go/src/github.com/odeke-em/drive/src/pull.go:265 +0x48c
```

**Comment by odeke-em** [comment] 2015-05-30 00:06
Hello @sselph, thank you for reporting this and welcome to drive!
For starters, `drive version`?

**Comment by sselph** [comment] 2015-05-30 00:12
drive version: 0.2.2
Commit Hash: 6bf8c18d3df601f34477bba9c17307cae44176b6
Go Version: go1.4.2 
OS: linux/amd64

**Comment by odeke-em** [comment] 2015-05-30 01:15
Thank you for the information, I'll take a look at it in a bit once am done with a code review here. Any special conditions you recall that might have triggered it?

**Comment by sselph** [comment] 2015-05-30 01:47
was just doing a `drive pull` but on a large number of files(1600+).

I think the issue is that `resp, err := r.transport.Client().Get(url)` results in an error(probably my poor bandwidth) and resp is a nil pointer so trying to reference resp.Body throws a panic.

**Comment by odeke-em** [comment] 2015-05-30 01:53
yeah, but it should return a value from which we should be able to read the statusCode from.
Otherwise nothing would ever be safe and we would have to check every single attribute before dereference -- see what I mean?
However, that's just an assumption, I'll dig in. Btw is this consistently reproducible? If so, please let me know and we can prepare a patch real quick to diagnose what happens.
Thanks.

**Comment by sselph** [comment] 2015-05-30 02:07
http://golang.org/src/net/http/client.go?s=9711:9771#L284
If there is an error the http.Client Get function will return nil for the *http.Response.

I worked around the issue to get everything downloaded but might be able to get it to reproduce by init'ing a new directory and trying again. Just let me know.

**Comment by odeke-em** [comment] 2015-05-30 02:11
Ah I see. Thank you for the investigation, good catch right there!
Would you like to submit a PR :) or would you like me to get it in?

**Comment by odeke-em** [comment] 2015-05-30 02:14
Since you did all the work of finding and investigating.

**Comment by sselph** [comment] 2015-05-30 02:19
I could and normally would but it would might take a couple days. I have to get permission from my employer and it is a Friday evening but if it can wait I'll start the process otherwise feel free to fix it.

**Comment by odeke-em** [comment] 2015-05-30 02:25
No worries, I totally understand.
The kind of error you identified is one that is critical because I've never encountered it and neither have other users (maybe because running < 1.4.2?) so I'd like to cover this base since even the lib sends back nil.
However, I'd like your acknowledgment to show (ideally I'd have wanted it to show in the contributor graphs). If it is fine with you in the next release I'll give you the credit there(I always do this during releases). If that works for you, I'll spin up a PR and you can rubber stamp it with your approval, and that will be another reference point.
Thank you!

**Comment by odeke-em** [comment] 2015-05-30 02:26
Actually I just saw that you forked drive so please go on with your plan :)

**Comment by odeke-em** [comment] 2015-05-30 09:21
@sselph thank you for reporting this and for the investigation. Addressed by https://github.com/odeke-em/drive/pull/218. Fix is present on master now. Please re-open if persists!

**Closed by odeke-em** 2015-05-30 09:21 UTC
Labels: bug

**Comment by sselph** [comment] 2015-05-30 09:37
Thanks for fixing. I threw in the request hoping someone was working late but I guess not. Thanks for maintaining this very useful drive client.

**Comment by odeke-em** [comment] 2015-05-30 09:42
I see. My bad, I just wanted to make sure that you would be able to use it without too many bugs without waiting for too long :) In the future, hopefully we'll get them on time. Please don't hesitate to reach out in case of any issues, questions or ideas. Thank you again.
